In [1]:
import pandas as pd

In [40]:
df = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/norman_2/results/allocation/norman_results_all.csv")

In [44]:
df_emb = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/norman_2/closest_embedding/norman_results_all.csv", index_col=0)
df_emb["condition"] = df_emb.index

In [48]:
dfs = []
for split in range(5):
    dfs.append(pd.read_csv(f"/lustre/groups/ml01/workspace/ot_perturbation/data/norman_2/cellflow/norman_results_all_{split}.csv"))
df_cf = pd.concat(dfs)

In [49]:
df_cf

,Unnamed: 0,encoded_ood_r_squared,encoded_ood_e_distance,encoded_ood_mmd,condition,decoded_ood_r_squared,decoded_ood_e_distance,decoded_ood_mmd,deg_ood_r_squared,deg_ood_e_distance,deg_ood_mmd,subgroup,model
0,AHR+KLF1,-2.094295,59.024155,0.081849,AHR+KLF1,0.954971,78.161240,0.069912,0.770982,25.451824,0.090677,double_seen_1,cellflow
1,ARID1A+ctrl,0.128587,12.246864,0.027546,ARID1A+ctrl,0.977682,34.120010,0.093325,0.925976,11.862838,0.072227,single,cellflow
2,BCL2L11+BAK1,-0.609100,15.300079,0.039142,BCL2L11+BAK1,0.987487,20.822144,0.063375,0.568147,0.289694,0.103918,double_seen_1,cellflow
3,BCL2L11+TGFBR2,-0.769495,14.439346,0.034308,BCL2L11+TGFBR2,0.988634,18.605667,0.059739,0.872672,7.593477,0.060653,double_seen_1,cellflow
4,BCL2L11+ctrl,-1.038890,13.327011,0.032908,BCL2L11+ctrl,0.989485,17.280930,0.060653,0.948875,1.011929,0.135662,single,cellflow
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,ctrl+PTPN9,0.629490,1.502270,0.008607,ctrl+PTPN9,0.995527,7.161613,0.068587,0.985685,1.393846,0.039688,single,cellflow
113,ctrl+RUNX1T1,-0.690193,11.317055,0.027753,ctrl+RUNX1T1,0.991248,14.353592,0.062499,0.937897,4.329297,0.051954,single,cellflow
114,ctrl+SAMD1,-1.381383,13.209988,0.029747,ctrl+SAMD1,0.986868,21.374504,0.092370,0.933416,9.644328,0.095277,single,cellflow
115,ctrl+UBASH3A,-0.016036,2.898529,0.009637,ctrl+UBASH3A,0.997257,4.418236,0.064749,0.999003,0.094911,0.028713,single,cellflow
116,ctrl+ZBTB25,0.304087,4.235737,0.015377,ctrl+ZBTB25,0.993741,10.126991,0.063557,0.954402,3.816007,0.035741,single,cellflow

In [50]:
df["model"].value_counts()

model
cellflow             1122
biolord               561
gears                 561
identity              561
scgpt                 561
closest_embedding     561
additive               64
Name: count, dtype: int64

In [51]:
df = df[df["model"]!="cellflow"]

In [52]:
df = pd.concat((df, df_cf, df_emb))

In [53]:
df_s = df[df["subgroup"]=="single"]

In [54]:
df_s[["model", "encoded_ood_e_distance", "decoded_ood_r_squared", "deg_ood_r_squared"]].groupby("model").mean()

,encoded_ood_e_distance,decoded_ood_r_squared,deg_ood_r_squared
model,,,
biolord,20.004289,0.969143,0.878983
cellflow,18.535870,0.982472,0.882946
closest_embedding,32.403917,0.966676,0.852737
gears,17.913590,0.979529,0.888557
identity,28.358846,0.976298,0.846370
scgpt,21.666171,0.978895,0.877159

In [ ]:
df_s[["model", "encoded_ood_mmd"]].groupby("model").mean()

In [ ]:
df_s[["model", "encoded_ood_mmd"]].groupby("model").mean()

In [55]:
df_d0 = df[df["subgroup"]=="double_seen_0"]

In [57]:
df_d0[["model", "encoded_ood_e_distance", "decoded_ood_r_squared", "deg_ood_r_squared"]].groupby("model").mean()

,encoded_ood_e_distance,decoded_ood_r_squared,deg_ood_r_squared
model,,,
biolord,41.544683,0.937300,-184.868278
cellflow,27.787794,0.972663,-82.808118
closest_embedding,50.158658,0.952643,-37.080507
gears,32.278726,0.959496,-541.893165
identity,64.222289,0.950372,-35.281995
scgpt,41.949575,0.963715,-53.317407

In [58]:
df_d1 = df[df["subgroup"]=="double_seen_1"]
df_d1[["model", "encoded_ood_e_distance", "decoded_ood_r_squared", "deg_ood_r_squared"]].groupby("model").mean()

,encoded_ood_e_distance,decoded_ood_r_squared,deg_ood_r_squared
model,,,
biolord,25.625659,0.964025,-24.269560
cellflow,20.995832,0.978919,-20.708996
closest_embedding,34.070054,0.968121,-8.499794
gears,21.986434,0.966460,-118.348021
identity,62.657669,0.951428,-7.351297
scgpt,31.844922,0.970232,-17.450354

In [59]:
df_d2 = df[df["subgroup"]=="double_seen_2"]
df_d2[["model", "encoded_ood_e_distance", "decoded_ood_r_squared", "deg_ood_r_squared"]].groupby("model").mean()

,encoded_ood_e_distance,decoded_ood_r_squared,deg_ood_r_squared
model,,,
additive,8.648598,0.989467,0.958599
biolord,8.382792,0.989400,0.957855
cellflow,5.426323,0.990600,0.949015
closest_embedding,34.892645,0.968401,0.843174
gears,10.256235,0.973730,0.915760
identity,61.433762,0.952080,0.704938
scgpt,17.285718,0.979765,0.896968

In [68]:
df_0 = dfs[0]
df_0[df_0["subgroup"]=="double_seen_2"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared     0.992068
encoded_ood_e_distance    3.864640
dtype: float64

In [69]:
df_1 = dfs[1]
df_1[df_1["subgroup"]=="double_seen_2"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared     0.994376
encoded_ood_e_distance    2.380657
dtype: float64

In [70]:
df_2 = dfs[2]
df_2[df_2["subgroup"]=="double_seen_2"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared      0.980843
encoded_ood_e_distance    17.501815
dtype: float64

In [71]:
df_3 = dfs[3]
df_3[df_3["subgroup"]=="double_seen_2"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared     0.989760
encoded_ood_e_distance    4.794469
dtype: float64

In [72]:
df_4 = dfs[4]
df_4[df_4["subgroup"]=="double_seen_2"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared     0.992081
encoded_ood_e_distance    2.965789
dtype: float64

In [73]:
df_0 = dfs[0]
df_0[df_0["subgroup"]=="single"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared      0.981369
encoded_ood_e_distance    18.449030
dtype: float64

In [74]:
df_1 = dfs[1]
df_1[df_1["subgroup"]=="single"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared      0.979763
encoded_ood_e_distance    23.909758
dtype: float64

In [75]:
df_2 = dfs[2]
df_2[df_2["subgroup"]=="single"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared      0.985550
encoded_ood_e_distance    13.165897
dtype: float64

In [76]:
df_3 = dfs[3]
df_3[df_3["subgroup"]=="single"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared      0.984652
encoded_ood_e_distance    14.001144
dtype: float64

In [77]:
df_4 = dfs[4]
df_4[df_4["subgroup"]=="single"][["decoded_ood_r_squared", "encoded_ood_e_distance"]].mean()

decoded_ood_r_squared      0.98126
encoded_ood_e_distance    22.53653
dtype: float64