In [1]:
import pandas as pd

In [4]:
batch_size=64
df = pd.read_csv(f"/lustre/groups/ml01/workspace/ot_perturbation/results/profiling/gpu_mem_benchmark_batch_size_{batch_size}.csv")

In [5]:
df.head()

,label,baseline_used_mb,peak_used_mb,incremental_peak_mb,iters,sample_interval_ms,elapsed_s,per_iter_ms
0,example,5316.0625,5316.0625,0.0,100,10.0,1.541295,15.412955

In [6]:
batch_size=128
df2 = pd.read_csv(f"/lustre/groups/ml01/workspace/ot_perturbation/results/profiling/gpu_mem_benchmark_batch_size_{batch_size}.csv")

In [7]:
df2

,label,baseline_used_mb,peak_used_mb,incremental_peak_mb,iters,sample_interval_ms,elapsed_s,per_iter_ms
0,example,5318.0625,5318.0625,0.0,100,10.0,1.577579,15.775794

In [14]:
dfs = []
for bs in [64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]:
    df = pd.read_csv(f"/lustre/groups/ml01/workspace/ot_perturbation/results/profiling/gpu_mem_benchmark_batch_size_{batch_size}.csv")
    df["batch_size"] = bs
    dfs.append(df)

In [15]:
pd.concat(dfs)

,label,baseline_used_mb,peak_used_mb,incremental_peak_mb,iters,sample_interval_ms,elapsed_s,per_iter_ms,batch_size
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,64
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,128
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,256
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,512
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,1024
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,2048
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,4096
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,8192
0,example,5316.0625,5316.0625,0.0,100,10.0,1.217014,12.170143,16384