In [3]:
import pandas as pd
import os

In [4]:
data_dir = "/lustre/groups/ml01/workspace/cell_flow_zebrafish/results/single_condition/cell_type_proportion_downstream"

In [5]:
df1 = pd.read_csv(os.path.join(data_dir,"logfoldchanges_tbx16_tbx16l_24.csv"))

In [6]:
df1.head()

,Unnamed: 0,index,ratio_oligo,ratio_true,logratio_true,logratio_pred,Oligo,timepoint,condition,gene_target,cell_type_broad_transfer,mode,ratio_pred,n_cells
0,0,neural progenitor (hindbrain),1.467817,1.392927,0.478120,0.553672,24h_tbx16-tbx16l_P13_H10,24.0,tbx16_tbx16l_24,tbx16_tbx16l,neural progenitor (hindbrain),single_oligo,NaN,7.471363
1,1,mesodermal progenitor cells (contains PSM),9.204935,10.903550,3.446726,3.202408,24h_tbx16-tbx16l_P13_H10,24.0,tbx16_tbx16l_24,tbx16_tbx16l,mesodermal progenitor cells (contains PSM),single_oligo,NaN,7.616776
2,2,neural progenitor (MHB),1.914366,1.791231,0.840952,0.936867,24h_tbx16-tbx16l_P13_H10,24.0,tbx16_tbx16l_24,tbx16_tbx16l,neural progenitor (MHB),single_oligo,NaN,6.869014
3,3,"eye, optic cup",1.452031,1.441845,0.527916,0.538072,24h_tbx16-tbx16l_P13_H10,24.0,tbx16_tbx16l_24,tbx16_tbx16l,"eye, optic cup",single_oligo,NaN,6.911747
4,4,head/eye connective tissue,1.440965,1.284102,0.360760,0.527035,24h_tbx16-tbx16l_P13_H10,24.0,tbx16_tbx16l_24,tbx16_tbx16l,head/eye connective tissue,single_oligo,NaN,6.786717

In [8]:
df1[["logratio_true", "logratio_pred"]].corr()

               logratio_true  logratio_pred
logratio_true       1.000000       0.849282
logratio_pred       0.849282       1.000000

In [9]:
df2 = pd.read_csv(os.path.join(data_dir,"logfoldchanges_tbx16_msgn1_18.csv"))

In [10]:
df2[["logratio_true", "logratio_pred"]].corr()

               logratio_true  logratio_pred
logratio_true       1.000000       0.813969
logratio_pred       0.813969       1.000000

In [11]:
df3 = pd.read_csv(os.path.join(data_dir,"logfoldchanges_smo_control_24.csv"))

In [12]:
df3[["logratio_true", "logratio_pred"]].corr()

               logratio_true  logratio_pred
logratio_true       1.000000       0.774359
logratio_pred       0.774359       1.000000

In [13]:
df4 = pd.read_csv(os.path.join(data_dir,"logfoldchanges_cdx4_cdx1a_36.csv"))

In [14]:
df4[["logratio_true", "logratio_pred"]].corr()

               logratio_true  logratio_pred
logratio_true       1.000000       0.746913
logratio_pred       0.746913       1.000000