In [3]:
import pandas as pd
import os
from scipy.stats import ttest_rel

In [2]:
df = pd.read_csv("/lustre/groups/ml01/workspace/ot_perturbation/data/zebrafish_new/results/allocation/all_models_metrics.csv", index_col=0)

In [4]:
df.head()

,fraction_cell_types_covered,cell_type_fraction_error,mean_r_sq_per_cell_type,mean_e_distance_per_cell_type,mean_mmd_per_cell_type,mean_sdiv_10_per_cell_type,mean_sdiv_100_per_cell_type,median_r_sq_per_cell_type,median_e_distance_per_cell_type,median_mmd_per_cell_type,...,e_distance_hypochord,mmd_hypochord,div_10_hypochord,div_100_hypochord,r_squared_hypophysis/locus coeruleus,e_distance_hypophysis/locus coeruleus,mmd_hypophysis/locus coeruleus,div_10_hypophysis/locus coeruleus,div_100_hypophysis/locus coeruleus,model
zc4h2_control_24,1.0,0.198075,0.997143,17.884346,0.007304,176.589351,50.130940,0.998086,10.724632,0.006735,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,id
met_control_36,1.0,0.290707,0.996653,21.373934,0.007520,196.086758,64.315720,0.997639,15.631581,0.006816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,id
tfap2a_control_72,1.0,0.321600,0.979980,127.018322,0.009210,338.764505,212.046395,0.996153,24.456763,0.007337,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,id
hgfa_control_48,1.0,0.348580,0.990385,55.715163,0.012429,239.495950,99.938459,0.993441,34.930590,0.011155,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,id
tfap2a_foxd3_72,1.0,0.229467,0.988895,92.352286,0.009099,292.229661,157.077969,0.994277,32.852069,0.007775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,id

In [8]:
data_dir = "/lustre/groups/ml01/workspace/cell_flow_zebrafish/results/single_condition/cell_type_proportion_downstream"

In [10]:
df = pd.read_csv(os.path.join(data_dir, "corrs_conditions_all.csv"))

In [11]:
df.head()

,Unnamed: 0,cell_type_broad,pearson,spearman,method,n_cells_mean,n_cells_var,quantile_bin_n_cells,quantile_pert_strength
0,0,head mesenchyme/PA cartilage,0.373862,0.431507,cellflow,317.171053,274.655391,Q3,Q3
1,1,head mesenchyme/PA cartilage,0.686513,0.705192,single_oligo,317.171053,274.655391,Q3,Q3
2,2,head mesenchyme/PA cartilage,-0.154115,-0.071216,mean,317.171053,274.655391,Q3,Q3
3,3,head mesenchyme/PA cartilage,0.584481,0.563873,cl,317.171053,274.655391,Q3,Q3
4,4,intestine,0.538647,0.536654,cellflow,376.802632,483.751865,Q3,Q3

In [17]:
len(df["cell_type_broad"].unique())

101

In [12]:
df.groupby("method")["pearson"].mean()

method
cellflow        0.466499
cl              0.422442
mean            0.023814
single_oligo    0.638510
Name: pearson, dtype: float64

In [19]:
unique_cts = df["cell_type_broad"].unique()

In [21]:
df.index = df["cell_type_broad"]

In [22]:
cf_stats = df[df["method"]=="cellflow"].loc[unique_cts]["pearson"].values
cl_stats = df[df["method"]=="cl"].loc[unique_cts]["pearson"].values

In [23]:
ttest_rel(cf_stats, cl_stats)

TtestResult(statistic=nan, pvalue=nan, df=nan)

In [25]:
cl_stats

array([ 0.58448123,  0.62403229, -0.33406856,  0.41899744,  0.03996108,
        0.38636044,  0.62751964,  0.84751219,  0.04606811, -0.13170403,
        0.26826899,  0.00869317,  0.25788272,  0.56395147, -0.0681484 ,
        0.51323231,  0.73771868,  0.54982801,  0.22982623,  0.48206321,
        0.81353371,  0.324874  ,  0.56882407,  0.75171281,  0.60670673,
        0.68065845, -0.04695416,  0.15849759,  0.43416506,  0.74476473,
        0.54334709,  0.10766599,  0.08685386,  0.34579674,  0.14071071,
        0.11875088,  0.58114003,  0.33453103,  0.57113997,  0.45025519,
        0.69457591,  0.55445847,  0.42323112,  0.6563778 ,  0.29929903,
        0.573399  ,  0.43992291,  0.46669822,  0.56774268, -0.16331535,
        0.17954838,  0.40164227,  0.64104664,  0.41310062,  0.54195356,
        0.30562168,  0.5957947 ,  0.51752488,  0.18134021,  0.08597874,
        0.25767873,  0.47648696,  0.66136524,  0.6164534 , -0.44424683,
        0.84959082,  0.61453693,  0.0933148 ,  0.38151599,  0.4944014 ,
        0.50668052,  0.57565398,  0.07335572,  0.25420194,  0.47323915,
        0.77720248,  0.32806975,  0.47338095,  0.69808527,  0.29894059,
        0.65621527,  0.57893572,  0.2563654 ,  0.72339971,  0.40944756,
        0.49175295,  0.50566772,  0.12146611,  0.68580371,  0.48357838,
        0.66787963,  0.71531671, -0.00845923,  0.12230162,  0.84682869,
        0.99195894,  0.73551447,  0.88079011,  0.15168295,         nan,
               nan])

In [27]:
import numpy as np
mask = ~np.isnan(cf_stats) & ~np.isnan(cl_stats)
a_clean = cf_stats[mask]
b_clean = cl_stats[mask]

In [28]:
ttest_rel(a_clean, b_clean)

TtestResult(statistic=1.3767648610686765, pvalue=0.1717221024360145, df=98)