In [1]:
import numpy as np

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import jax
import functools
import matplotlib.pyplot as plt
import anndata as ad
import scanpy as sc
import rapids_singlecell as rsc
import flax.linen as nn
import optax
import cellflow
from cellflow.model import CellFlow
import cellflow.preprocessing as cfpp
from cellflow.utils import match_linear
from cellflow.plotting import plot_condition_embedding
from cellflow.preprocessing import transfer_labels, compute_wknn, centered_pca, project_pca, reconstruct_pca
from cellflow.metrics import compute_r_squared, compute_e_distance

/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/optuna/study/_optimize.py:29: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from optuna import progress_bar as pbar_module
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)

In [51]:
def compute_frechet_var(x: dict[int, np.ndarray]):
    pairwise_e_dists = []
    denominator = 2 * len(x)**2
    for s1 in x.values():
        for s2 in x.values():
            pairwise_e_dists.append(compute_e_distance(s1, s2)**2)
    return np.sum(np.array(pairwise_e_dists))/denominator

def compute_metrics(adata_ref: ad.AnnData, adata_pred_all_samples: ad.AnnData, donor_deg_dict: dict, adata_ood_true: ad.AnnData, adata_ctrl: ad.AnnData, n_neighbors: int=1, cell_type_col: str = "cell_type_new", min_cells_for_dist_metrics: int = 50) -> dict:
    
    compute_wknn(ref_adata=adata_ref, query_adata=adata_pred_all_samples, n_neighbors=n_neighbors, ref_rep_key="X_pca", query_rep_key="X_pca_for_ct_transfer")
    transfer_labels(query_adata=adata_pred_all_samples, ref_adata=adata_ref, label_key=cell_type_col)
    
    dict_to_log = {}
    
    ood_e_distances = []
    decoded_ood_r_squareds = []
    mean_decoded_r_sq_per_cell_types = []
    mean_e_distance_per_cell_types = []
    mean_deg_r_sq_per_cell_types = []

    for i in range(5):
        print(i)
        adata_pred = adata_pred_all_samples[adata_pred_all_samples.obs["sample"]==i]
        # standard metrics
        print(len(adata_pred), len(adata_ood_true))
        ood_e_distance = compute_e_distance(adata_ood_true.obsm["X_pca"], adata_pred.obsm["X_pca"])
        decoded_ood_r_squared = compute_r_squared(adata_ood_true.X.toarray(), adata_pred.layers["X_recon"])

        r_sq = {}
        e_distance = {}
        deg_r_sq = {}
        
        for ct_cyto in donor_deg_dict.keys(): 
            cell_type = ct_cyto.split("_")[1]
            adata_true_ct = adata_ood_true[(adata_ood_true.obs[f"{cell_type_col}"]==cell_type)]
            adata_pred_ct = adata_pred[adata_pred.obs[f"{cell_type_col}_transfer"]==cell_type]
            if ((adata_true_ct.n_obs == 0) or adata_pred_ct.n_obs==0):
                continue
            if adata_pred_ct.n_obs == 0:
                continue
            dist_true_decoded = adata_true_ct.X.toarray()
            dist_pred_decoded = adata_pred_ct.X
            dist_true = adata_true_ct.obsm["X_pca"]
            dist_pred = adata_pred_ct.obsm["X_pca"]
            r_sq[f"decoded_r_squared_{cell_type}"] = compute_r_squared(dist_true_decoded, dist_pred_decoded)
            e_distance[f"e_distance_{cell_type}"] = compute_e_distance(dist_true, dist_pred)
            
            deg_mask = [True if el in donor_deg_dict[ct_cyto] else False for el in adata_ood_true.var_names]
            deg_true_decoded = adata_true_ct[:,deg_mask].X.toarray()
            deg_pred_decoded = adata_pred_ct[:,deg_mask].X
            deg_r_sq[f"deg_decoded_r_squared_{cell_type}"] = compute_r_squared(deg_true_decoded, deg_pred_decoded)

        ood_e_distances.append(ood_e_distance)
        decoded_ood_r_squareds.append(decoded_ood_r_squared)
        mean_decoded_r_sq_per_cell_types.append(np.mean(list(r_sq.values())))
        mean_e_distance_per_cell_types.append(np.mean(list(e_distance.values())))
        mean_deg_r_sq_per_cell_types.append(np.mean(list(deg_r_sq.values())))

    # metrics to return
    dict_to_log["ood_e_distance"] = np.mean(ood_e_distances)
    dict_to_log["decoded_ood_r_squared"] = np.mean(decoded_ood_r_squareds)

    dict_to_log["mean_decoded_r_sq_per_cell_type"] = np.mean(mean_decoded_r_sq_per_cell_types)
    dict_to_log["mean_e_distance_per_cell_type"] = np.mean(mean_e_distance_per_cell_types)
    dict_to_log["mean_deg_r_sq_per_cell_type"] = np.mean(mean_deg_r_sq_per_cell_types)

    distr_dict = {}
    distr_dict_per_cell_type = {}
    gex_dict = {}
    gex_dict_per_cell_type = {}
    deg_gex_per_cell_type = {}
    for sample_idx in range(5):
        adata_pred = adata_pred_all_samples[adata_pred_all_samples.obs["sample"]==sample_idx]
        distr_dict[sample_idx] = adata_pred.obsm["X_pca"]
        gex_dict[sample_idx] = np.mean(adata_pred.X, axis=0)
        for ct in adata_pred.obs[f"{cell_type_col}_transfer"].unique():
            adata_pred_ct = adata_pred[adata_pred.obs[f"{cell_type_col}_transfer"]==ct]
            if ct not in distr_dict_per_cell_type:
                distr_dict_per_cell_type[ct] = {}
            distr_dict_per_cell_type[ct][sample_idx] = adata_pred_ct.obsm["X_pca"]
            if ct not in gex_dict_per_cell_type:
                gex_dict_per_cell_type[ct] = {}
            gex_dict_per_cell_type[ct][sample_idx] = np.mean(adata_pred_ct.X, axis=0)
            if ct not in deg_gex_per_cell_type:
                deg_gex_per_cell_type[ct] = {}
            deg_mask = [True if el in donor_deg_dict[ct_cyto] else False for el in adata_ood_true.var_names]
            deg_gex_per_cell_type[ct][sample_idx] = np.mean(adata_pred_ct[:,deg_mask].X, axis=0)
            

    dict_to_log["frechet_variance"] = compute_frechet_var(distr_dict)
    dict_to_log["var_mean_gex"] = np.var(np.stack(list(gex_dict.values())), axis=0).mean()
    f_var_per_cell_types = []

    for ct, distr_ct in distr_dict_per_cell_type.items():
        f_var_ct = compute_frechet_var(distr_ct)
        f_var_per_cell_types.append(f_var_ct)
        dict_to_log[f"frechet_variance_{ct}"] = f_var_ct

    dict_to_log["mean_frechet_variance_per_cell_type"] = np.mean(f_var_per_cell_types)
    
    var_mean_gex_per_cell_types = []
    var_mean_deg_gex_per_cell_types = []
    for ct, gex_ct in gex_dict_per_cell_type.items():
        var_mean_gex_ct = np.var(np.stack(list(gex_ct.values())), axis=0).mean()
        var_mean_gex_per_cell_types.append(var_mean_gex_ct)
        dict_to_log[f"var_mean_gex_{ct}"] = var_mean_gex_ct
        deg_gex_ct = deg_gex_per_cell_type[ct]
        var_mean_deg_gex_ct = np.var(np.stack(list(deg_gex_ct.values())), axis=0).mean()
        var_mean_deg_gex_per_cell_types.append(var_mean_deg_gex_ct)
        dict_to_log[f"var_mean_deg_gex_{ct}"] = var_mean_deg_gex_ct

    dict_to_log["mean_var_mean_gex_per_cell_type"] = np.mean(var_mean_gex_per_cell_types)
    dict_to_log["mean_var_mean_deg_gex_per_cell_type"] = np.mean(var_mean_deg_gex_per_cell_types)

    
    return dict_to_log, distr_dict, gex_dict # remove last three

In [3]:
cytokine_held_out = "TWEAK"
idx_given_cytokine = "7"
control_key = "is_control"

adata_base = sc.read_h5ad(f"/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/new_cytokine/adata_base_{cytokine_held_out}.h5ad")
adata_rest = sc.read_h5ad(f"/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/new_cytokine/adata_rest_{cytokine_held_out}.h5ad")
cellflow.preprocessing.centered_pca(adata_base, n_comps=100, method="rapids", keep_centered_data=False)
cellflow.preprocessing.project_pca(query_adata=adata_rest, ref_adata=adata_base)

In [4]:
idx_given_cytokine = "7"

In [5]:
donors_to_impute = adata_rest.uns["split_info"][idx_given_cytokine]["donors_to_impute"]
donors_to_train_data = adata_rest.uns["split_info"][idx_given_cytokine]["donors_to_train_data"]
adata_to_append = adata_rest[adata_rest.obs["donor"].isin(donors_to_train_data)]
adata_train = ad.concat((adata_base, adata_to_append))
adata_train.uns = adata_base.uns.copy()
adata_ood_perturbed = adata_rest[adata_rest.obs["donor"].isin(donors_to_impute)]

adata_ctrl = adata_train[adata_train.obs[control_key].to_numpy()]

adata_ctrl_subsetted = []
for donor in adata_ctrl.obs["donor"].unique():
    adata_tmp = adata_ctrl[adata_ctrl.obs["donor"]==donor]
    if adata_tmp.n_obs > 10000:
        sc.pp.subsample(adata_tmp, n_obs=10000)
    adata_ctrl_subsetted.append(adata_tmp)
adata_ctrl = ad.concat(adata_ctrl_subsetted)


adata_train.uns = adata_train.uns.copy()
adata_ctrl.uns = adata_train.uns.copy()
adata_ood_perturbed.uns = adata_train.uns.copy()


cf = CellFlow(adata_train, solver="otfm")

perturbation_covariates = {"cytokines": ["cytokine"]}
split_covariates = ["donor"]

cf.prepare_data(
    sample_rep="X_pca",
    control_key=control_key,
    perturbation_covariates=perturbation_covariates,
    perturbation_covariate_reps={"cytokines": "esm2_embeddings"},
    sample_covariates=("donor",),
    sample_covariate_reps={"donor": "donor_one_hot"},
    split_covariates=split_covariates,
)

[########################################] | 100% Completed | 103.07 ms
[########################################] | 100% Completed | 2.61 sms
[########################################] | 100% Completed | 208.95 ms

In [6]:
match_fn = functools.partial(
    match_linear,
    epsilon=10.0, #config_dict["model"]["epsilon"],
    scale_cost="mean",
    tau_a=1.0, #config_dict["model"]["tau_a"],
    tau_b=1.0, #config_dict["model"]["tau_b"]
)
#optimizer = optax.MultiSteps(optax.adam(config_dict["model"]["learning_rate"]), config_dict["model"]["multi_steps"])
#flow = {config_dict["model"]["flow_type"]: config_dict["model"]["flow_noise"]}
optimizer = optax.MultiSteps(optax.adam(1e-4), 20)
flow = {"constant_noise": 0.1}


#layers_before_pool = config_dict["model"]["layers_before_pool"]
#layers_after_pool = config_dict["model"]["layers_after_pool"]

layers_before_pool = {
    "cytokines": {"layer_type": "mlp", "dims": [1024, 1024], "dropout_rate": 0.5}, # cytokine_treatment replaced by cytokines 
    "donor": {"layer_type": "mlp", "dims": [256, 256], "dropout_rate": 0.0},
}

layers_after_pool = {
    "layer_type": "mlp", "dims": [1024, 1024], "dropout_rate": 0.0,
}

In [7]:
cf.prepare_model(
    condition_mode="stochastic",
    regularization=0.01,
    pooling="attention_token",
    pooling_kwargs={},
    layers_before_pool=layers_before_pool,
    layers_after_pool=layers_after_pool,
    condition_embedding_dim=256,
    cond_output_dropout=0.9,
    condition_encoder_kwargs={},
    pool_sample_covariates=True,
    time_freqs=1024,
    time_encoder_dims=[1024, 1024, 1024],
    time_encoder_dropout=0.0,
    hidden_dims=[2048, 2048, 2048],
    hidden_dropout=0.0,
    conditioning="concatenation",
    decoder_dims=[4096, 4096, 4096],
    vf_act_fn=nn.silu,
    vf_kwargs=None,
    probability_path={"constant_noise": 0.5},
    match_fn=match_fn,
    optimizer=optax.MultiSteps(optax.adam(5e-5), 20),
    solver_kwargs={},
    layer_norm_before_concatenation=False,
    linear_projection_before_concatenation=False,
)

In [14]:
adata_test = adata_ood_perturbed
adatas_train_subsampled = []
for cond in adata_train.obs["condition"].unique(): # as we have many conditions, this might take a few minutes
    adatas_train_subsampled.append(sc.pp.subsample(adata_train[adata_train.obs["condition"]==cond], n_obs=1000, copy=True))

adata_train_for_validation = ad.concat(adatas_train_subsampled)

adatas_test_subsampled = []
for cond in adata_test.obs["condition"].unique():
    adatas_test_subsampled.append(sc.pp.subsample(adata_test[adata_test.obs["condition"]==cond], n_obs=2000, copy=True))

for cond in adata_ctrl.obs["condition"].unique():
    adatas_test_subsampled.append(sc.pp.subsample(adata_ctrl[adata_ctrl.obs["condition"]==cond], n_obs=2000, copy=True))
adata_test_for_validation = ad.concat(adatas_test_subsampled)

In [12]:
adata_ctrl.obs["condition"].unique()

['Donor10_PBS', 'Donor11_PBS', 'Donor12_PBS', 'Donor1_PBS', 'Donor2_PBS', ..., 'Donor5_PBS', 'Donor6_PBS', 'Donor7_PBS', 'Donor8_PBS', 'Donor9_PBS']
Length: 12
Categories (12, object): ['Donor1_PBS', 'Donor2_PBS', 'Donor3_PBS', 'Donor4_PBS', ..., 'Donor9_PBS', 'Donor10_PBS', 'Donor11_PBS', 'Donor12_PBS']

In [13]:
cond

'Donor10_PBS'

In [15]:
adata_test_for_validation.uns = adata_test.uns.copy()

cf.prepare_validation_data(
    adata_test_for_validation,
    name="test",
    n_conditions_on_log_iteration=None,
    n_conditions_on_train_end=None,
)

[########################################] | 100% Completed | 101.82 ms
[########################################] | 100% Completed | 101.52 ms
[########################################] | 100% Completed | 100.86 ms

In [20]:
from cellflow.data._dataloader import OOCTrainSampler, PredictionSampler, TrainSampler, ValidationSampler
validation_loaders = {k: ValidationSampler(v) for k, v in cf.validation_data.items() if k != "predict_kwargs"}

In [35]:
validation_loaders.keys()

dict_keys(['train', 'test'])

In [25]:
batch = validation_loaders["test"].sample(mode="on_log_iteration")

In [28]:
len(batch["condition"])

9

In [131]:
import scipy 
from typing import Any
from cellflow.training import ComputationCallback
from cellflow._types import ArrayLike
from cellflow.solvers import _genot, _otfm
import jax.tree_util as jtu
import wandb
import numpy as np

def wandb_scatter(x, y, *, x_name: str, y_name: str, title: str, step: int | None = None):
    x = np.asarray(x).reshape(-1)
    y = np.asarray(y).reshape(-1)

    table = wandb.Table(data=[[float(xi), float(yi)] for xi, yi in zip(x, y)],
                        columns=[x_name, y_name])

    plot = wandb.plot.scatter(table, x_name, y_name, title=title)
    payload = {title: plot}
    if step is None:
        wandb.log(payload)
    else:
        wandb.log(payload, step=step)
        
def compute_frechet_var(x: dict[int, np.ndarray]):
    pairwise_e_dists = []
    denominator = 2 * len(x)**2
    for s1 in x.values():
        for s2 in x.values():
            pairwise_e_dists.append(compute_e_distance(s1, s2)**2)
    return np.sum(np.array(pairwise_e_dists))/denominator
    
class VarCallback(ComputationCallback):
    def __init__(self, val_data: dict[str, ValidationSampler], ref_adata: ad.AnnData, n_draws: int = 10, predict_kwargs: dict[str, Any] = {}):
        self.n_draws = n_draws
        self.val_data = val_data
        self.pcs = ref_adata.varm["PCs"]
        self.means = ref_adata.varm["X_mean"]
        self.reconstruct_data = lambda x: x @ np.transpose(self.pcs) + np.transpose(self.means)
        self.predict_kwargs = predict_kwargs

    def on_train_begin(self, *args, **kwargs):
        pass

    def on_train_end(self, *args, **kwargs):
        return self.on_log_iteration(valid_source_data, valid_true_data, valid_pred_data, solver)

    def on_log_iteration(
        self, 
        valid_source_data: dict[str, dict[str, ArrayLike]],
        valid_true_data: dict[str, dict[str, ArrayLike]],
        valid_pred_data: dict[str, dict[str, ArrayLike]],
        solver: _otfm.OTFlowMatching | _genot.GENOT,
    ) -> dict[str, float]:
        valid_source_data: dict[str, dict[str, ArrayLike]] = {}
        valid_pred_data: dict[str, dict[str, ArrayLike]] = {}
        valid_true_data: dict[str, dict[str, ArrayLike]] = {}

        
        metrics = {}
        for val_key, vdl in self.val_data.items():
            mean_e_dists = []
            mean_r_sqs = []
            frechet_var = []
            var_gex = []
            batch = vdl.sample(mode="on_log_iteration")
            for cond in batch["source"].keys():
                e_distances = []
                r_sqs = []
                src = batch["source"][cond]
                condition = batch["condition"][cond]
                true_tgt = batch["target"][cond]
                valid_pred_data[cond] = {}
                for i in range(self.n_draws):
                    valid_pred_data[cond][i] = solver.predict(src, condition=condition,rng=jax.random.PRNGKey(i), **self.predict_kwargs)
                frechet_var.append(compute_frechet_var(valid_pred_data[cond]))
                for i in range(self.n_draws):
                    e_distances.append(compute_e_distance(true_tgt, valid_pred_data[cond][i]))
                valid_true_data_decoded = self.reconstruct_data(true_tgt)
                valid_pred_data_decoded = jtu.tree_map(self.reconstruct_data, valid_pred_data[cond])
                var_gex.append(np.var(np.stack(list(valid_pred_data_decoded.values())), axis=0).mean())
                for i in range(self.n_draws):
                    r_sqs.append(compute_r_squared(valid_true_data_decoded, valid_pred_data_decoded[i]))
                
                mean_r_sqs.append(np.mean(r_sqs))
                mean_e_dists.append(np.mean(e_distances))
                print(mean_r_sqs, r_sqs)

            metrics[f"{val_key}_e_dist"] = np.mean(mean_e_dists)
            metrics[f"{val_key}_r_sq"] = np.mean(mean_r_sqs)
            metrics[f"{val_key}_pearson_calibration"] = np.corrcoef(np.array(mean_e_dists), np.array(frechet_var))[0,1]
            metrics[f"{val_key}_spearman_calibration"] = scipy.stats.spearmanr(np.array(mean_e_dists), np.array(frechet_var)).statistic
            metrics[f"{val_key}_pearson_decoded_calibration"] = np.corrcoef(np.array(mean_r_sqs), -np.array(var_gex))[0,1]
            metrics[f"{val_key}_spearman_decoded_calibration"] = scipy.stats.spearmanr(np.array(mean_r_sqs), -np.array(var_gex)).statistic

            wandb_scatter(
                x=frechet_var,
                y=mean_e_dists,
                x_name="frechet_var",
                y_name="mean_e_dist",
                title=f"{val_key}/calibration_e_dist_vs_frechet_var",
            )
            
            wandb_scatter(
                x=var_gex,
                y=mean_r_sqs,
                x_name="var_gex",
                y_name="mean_r_sq",
                title=f"{val_key}/decoded_calibration_r_sq_vs_var_gex",
            )

            
        return metrics

In [132]:
class DummySolver:
    def __init__(self):
        pass

    def predict(*args, **kwargs):
        return np.random.rand(20,100)

In [133]:
#cb = VarCallback({"test": ValidationSampler(cf.validation_data["test"])}, ref_adata = adata_base, n_draws=10)

In [149]:
adata_ood = ad.concat((adata_ctrl, adata_ood_perturbed))
adata_ood.uns = adata_train.uns.copy()

cb = VarCallback({"test": ValidationSampler(cf.validation_data["test"])}, ref_adata = adata_base, n_draws=10)
wandb_callback = cellflow.training.WandbLogger(project="pbmc_with_uncertainty", out_dir="/home/icb/dominik.klein/tmp", config={})

In [151]:
callbacks = [cb, wandb_callback]

cf.train(
        num_iterations=100_000,
        batch_size=1024,
        callbacks=callbacks,
        valid_freq=25_000,
    )

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: mucdk (modality_translation) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

 25%|██▍       | 24996/100000 [08:19<20:47, 60.12it/s]

[0.9884964736295834] [0.9883533275840586, 0.9883549724415056, 0.9893755525168324, 0.9882072080114116, 0.9883576693637146, 0.9882184614887876, 0.9884528402983436, 0.9884408618020222, 0.9886806859618674, 0.9885231568272894]
[0.9884964736295834, 0.9830747058600077] [0.9826221569842432, 0.9828293945606901, 0.9835838229862737, 0.9825420562383234, 0.9829789549130031, 0.983353353974559, 0.9834236027872869, 0.9831550286309724, 0.9830688110450032, 0.9831898764797213]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568] [0.9846860254453389, 0.9847121822214089, 0.9851126908799379, 0.9844657801891535, 0.9847122686204557, 0.9845015920412055, 0.9848745246090929, 0.9848387758859182, 0.9848914988806708, 0.9847318174003855]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568, 0.9908179940866642] [0.99029839485233, 0.9906420679540255, 0.9913801399772565, 0.9900612854365181, 0.9909026056736118, 0.9908737595839195, 0.9908640207301352, 0.9908657208516165, 0.9912854487321314, 0.9910064970750974]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568, 0.9908179940866642, 0.9819423934101277] [0.9819529335933708, 0.9817762443496838, 0.9823173427116101, 0.9815482187695418, 0.9818706732483584, 0.9816144586763986, 0.9820167099343048, 0.9821205436784781, 0.982179053792033, 0.9820277553474978]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568, 0.9908179940866642, 0.9819423934101277, 0.9822289254431681] [0.9824131116499766, 0.9824497284348366, 0.9813899702034722, 0.9829316157983508, 0.9822252769530657, 0.9820870538194102, 0.9823943661222952, 0.9823010734651166, 0.9817888557170477, 0.9823082022681091]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568, 0.9908179940866642, 0.9819423934101277, 0.9822289254431681, 0.9823028643816617] [0.9816924271660504, 0.9820473344999358, 0.9832808200966726, 0.9812518894675455, 0.9825153718723155, 0.9823953602036537, 0.9822084033885544, 0.9822749860371737, 0.9829140034130456, 0.9824480476716683]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568, 0.9908179940866642, 0.9819423934101277, 0.9822289254431681, 0.9823028643816617, 0.9736542885951242] [0.972779874625744, 0.9729715642718139, 0.9753338829422772, 0.9729547744237554, 0.9741243625659395, 0.972839120514713, 0.9731321521393138, 0.974496264637433, 0.9746329044754056, 0.9732779853548463]
[0.9884964736295834, 0.9830747058600077, 0.9847527156173568, 0.9908179940866642, 0.9819423934101277, 0.9822289254431681, 0.9823028643816617, 0.9736542885951242, 0.9825619764190894] [0.9829224311258279, 0.9826012970228749, 0.981934923499539, 0.9827496968651072, 0.9825853814735106, 0.9826194157319931, 0.9826316994154617, 0.9826102715657294, 0.9821345370469525, 0.9828301104438952]

 50%|█████     | 50001/100000 [1:04:18<13:28, 61.84it/s, loss=7.38]

[0.9886204105144536] [0.988943043758926, 0.9886559264183001, 0.9887627296798525, 0.9888325811079847, 0.9874918691609891, 0.9886437622231191, 0.9887662210653213, 0.9887726744318922, 0.9885647954569022, 0.9887705018412488]
[0.9886204105144536, 0.975808575856723] [0.9761209747998394, 0.9763230457170136, 0.9762775556737288, 0.9760002876013848, 0.9725595679062464, 0.9760955670704224, 0.9759727978617442, 0.9755094670431393, 0.9767877710111051, 0.9764387238826049]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169] [0.9818872729253875, 0.981885827400007, 0.9813020308137658, 0.9821216878966441, 0.9821071028302575, 0.9812385696556439, 0.9813266932530148, 0.9815212206908656, 0.9812277748586762, 0.9811768829229072]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169, 0.9889279204004978] [0.9890537491229102, 0.9889284499682373, 0.9889343381603499, 0.9892073331449596, 0.989570818639003, 0.9884752748284898, 0.9886779677611545, 0.9890622040778002, 0.9886981839910621, 0.9886708843110104]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169, 0.9889279204004978, 0.9879651217470261] [0.9882030258780021, 0.9882158102185636, 0.9879620000031317, 0.9880748379850527, 0.9873881452831538, 0.9878745945905268, 0.9878893893509987, 0.9879829324183901, 0.9880849755140395, 0.9879755062284028]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169, 0.9889279204004978, 0.9879651217470261, 0.9903125619590132] [0.9905581955064428, 0.990352986727026, 0.9902773122379528, 0.9905609634746374, 0.9908392418600501, 0.9899050412304442, 0.9902825434725413, 0.9903658357245084, 0.9901607402184253, 0.989822759138103]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169, 0.9889279204004978, 0.9879651217470261, 0.9903125619590132, 0.9850342043612752] [0.9851758740270187, 0.9852155847744974, 0.9851906990226225, 0.9853013236520893, 0.9839146578022521, 0.9851867492663762, 0.9850226528368514, 0.9850587444473157, 0.9853803350960841, 0.9848954226876446]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169, 0.9889279204004978, 0.9879651217470261, 0.9903125619590132, 0.9850342043612752, 0.9754467694577615] [0.9756221286375468, 0.9757288965323215, 0.9749791088871738, 0.9758404480233296, 0.9765714542262207, 0.9748402278687109, 0.9754583803142965, 0.9754287796679101, 0.9752634604296222, 0.9747348099904829]
[0.9886204105144536, 0.975808575856723, 0.9815795063247169, 0.9889279204004978, 0.9879651217470261, 0.9903125619590132, 0.9850342043612752, 0.9754467694577615, 0.9784216081608935] [0.9783384585438895, 0.9785869492934931, 0.9780917397269443, 0.9785811443465121, 0.9786905006950117, 0.9784818668902507, 0.9783694873465605, 0.9786182505516735, 0.9784336601276371, 0.9780240240869628]

 75%|███████▍  | 74998/100000 [2:00:12<06:51, 60.81it/s, loss=6.47]

[0.9788703079717029] [0.9777138737179691, 0.9793173530732838, 0.9784261683237807, 0.978924359083478, 0.9793234540729042, 0.9789967314543087, 0.9787828018795313, 0.9791462681402427, 0.9787011262031682, 0.9793709437683621]
[0.9788703079717029, 0.9806261108228617] [0.9793667534647055, 0.9813957952605237, 0.9799534395442826, 0.9805437568498164, 0.9810158834401833, 0.980923887367453, 0.9806806317249236, 0.9809527643402088, 0.9803600307378941, 0.9810681654986246]
[0.9788703079717029, 0.9806261108228617, 0.9871528357782129] [0.9872961088820721, 0.9868316297881018, 0.9873950375603884, 0.9870377579809979, 0.9871601073453841, 0.9871282372344798, 0.9872083696240301, 0.9871385743212555, 0.9870686938152179, 0.987263841230202]
[0.9788703079717029, 0.9806261108228617, 0.9871528357782129, 0.981796261522349] [0.9815068451040233, 0.9819498846291783, 0.9817179639288203, 0.9816233789518548, 0.9817125521378615, 0.9819912313292785, 0.9817963091949077, 0.9819304114726985, 0.9817897114783053, 0.9819443269965618]
[0.9788703079717029, 0.9806261108228617, 0.9871528357782129, 0.981796261522349, 0.9824946912727868] [0.9829268034541262, 0.9824660805032915, 0.9827464901784695, 0.9825943698774572, 0.9820940409625741, 0.9823356806813387, 0.9824692755856602, 0.9824647541748345, 0.9823346879375418, 0.9825147293725727]
[0.9788703079717029, 0.9806261108228617, 0.9871528357782129, 0.981796261522349, 0.9824946912727868, 0.9741044181801769] [0.9722272557468501, 0.9741593857102085, 0.9737112388577919, 0.9742051717838293, 0.9744951100063577, 0.9746856791627885, 0.974514075105372, 0.9743041582160882, 0.9740494776058674, 0.9746926296066146]
[0.9788703079717029, 0.9806261108228617, 0.9871528357782129, 0.981796261522349, 0.9824946912727868, 0.9741044181801769, 0.9891524036584768] [0.9880370137723091, 0.9894564539588493, 0.9890234859161938, 0.989107413714128, 0.989467662460234, 0.9892676357960327, 0.9893667062431086, 0.9888592790239166, 0.9893141611276622, 0.9896242245723326]
[0.9788703079717029, 0.9806261108228617, 0.9871528357782129, 0.981796261522349, 0.9824946912727868, 0.9741044181801769, 0.9891524036584768, 0.9879817892967646] [0.9872807888178806, 0.9882101993763058, 0.9879766384409238, 0.9881285992111639, 0.9877614068708542, 0.9880770311667907, 0.9882435369787823, 0.9880444115892099, 0.9879898622077188, 0.9881054183080148]

 75%|███████▌  | 75004/100000 [2:48:42<875:40:36, 126.12s/it, loss=6.27]

[0.9788703079717029, 0.9806261108228617, 0.9871528357782129, 0.981796261522349, 0.9824946912727868, 0.9741044181801769, 0.9891524036584768, 0.9879817892967646, 0.9827640458818389] [0.982391626933172, 0.9832925824343233, 0.9825722764958769, 0.9828483951182125, 0.9829111924741615, 0.9827501327627972, 0.9826333606638721, 0.9828159145070102, 0.9824765524733897, 0.9829484249555738]

100%|██████████| 100000/100000 [2:55:32<00:00,  9.49it/s, loss=6.27]

TypeError: 'NoneType' object is not iterable

In [14]:
adata_ctrl = ad.concat(adata_ctrl_subsetted)
sc.pp.subsample(adata_ctrl, n_obs=300)
adata_ctrl.uns = adata_train.uns.copy()

In [15]:
preds = []
covariate_data = adata_ood_perturbed.obs.drop_duplicates(subset=["condition"])

for i in range(5):
    preds.append(cf.predict(adata=adata_ctrl, sample_rep="X_pca", condition_id_key="condition", rng=jax.random.PRNGKey(i), covariate_data=covariate_data))

[########################################] | 100% Completed | 101.63 ms
[########################################] | 100% Completed | 100.60 ms
[########################################] | 100% Completed | 101.64 ms
[########################################] | 100% Completed | 101.19 ms
[########################################] | 100% Completed | 109.15 ms
[########################################] | 100% Completed | 100.87 ms
[########################################] | 100% Completed | 102.96 ms
[########################################] | 100% Completed | 101.16 ms
[########################################] | 100% Completed | 101.58 ms
[########################################] | 100% Completed | 101.09 ms

In [16]:
import pickle
adatas_preds_all = []
for i, pred in enumerate(preds):
    adata_preds = []
    for cond, array in pred.items():
    
        obs_data = pd.DataFrame({
            'condition': [cond] * array.shape[0]
        })
        adata_pred = ad.AnnData(X=np.empty((len(array),adata_train.n_vars)), obs=obs_data)
        adata_pred.obsm["X_pca"] = np.squeeze(array)
        adata_preds.append(adata_pred)
    
    adata_preds = ad.concat(adata_preds)
    adata_preds.obs["sample"] = i
    adata_preds.var_names = adata_train.var_names
    adatas_preds_all.append(adata_preds)

    
adata_pred_all = ad.concat(adatas_preds_all)

with open("/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/degs.pkl", "rb") as pickle_file:
    deg_genes = pickle.load(pickle_file)

with open("/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/idcs_to_keep.pkl", "rb") as pickle_file:
    idcs_to_keep = pickle.load(pickle_file)

/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [18]:
cytokine=cytokine_held_out
adata_full = sc.read_h5ad("/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/pbmc_with_pca.h5ad")

In [54]:
adata_full.obsm#["X_pca"].shape

AxisArrays with keys: X_pca

In [19]:
with open("/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/idcs_to_keep.pkl", "rb") as pickle_file:
    idcs_to_keep = pickle.load(pickle_file)

adata_ref = adata_full[adata_full.obs_names.isin(idcs_to_keep)]

In [20]:
cellflow.preprocessing.reconstruct_pca(query_adata=adata_pred_all, ref_adata=adata_base, use_rep="X_pca", layers_key_added = "X_recon")
adata_pred_all.X = adata_pred_all.layers["X_recon"]
project_pca(query_adata=adata_pred_all, ref_adata=adata_ref, obsm_key_added="X_pca_for_ct_transfer")
project_pca(query_adata=adata_pred_all, ref_adata=adata_full, obsm_key_added="X_pca")

In [40]:
#adata_ood_perturbed.obs["cell_type_new"] = adata_ood_perturbed.obs["cell_type"]

In [37]:
project_pca(query_adata=adata_ood_perturbed, ref_adata=adata_full, obsm_key_added="X_pca")

/ictstr01/home/icb/dominik.klein/git_repos/cell_flow_perturbation/src/cellflow/preprocessing/_pca.py:201: ImplicitModificationWarning: Setting element `.obsm['X_pca']` of view, initializing view as actual.
  query_adata.obsm[obsm_key_added] = np.array((X - np.transpose(np.array(ref_means))) @ np.array(ref_pcs))

In [52]:
# TODO: frechet variance in orig 100dim space, not in eval space as we don't have access to it

distr_dicts = {}
gex_dicts = {}
out_dicts = {}
for condition in adata_pred_all.obs["condition"].unique():
    cytokine=cytokine_held_out
    donor=condition.split("_")[0]
    adata_ood_true_cond = adata_ood_perturbed[(adata_ood_perturbed.obs["donor"] == donor) & (adata_ood_perturbed.obs["cytokine"]==cytokine)]
    donor_deg_dict = {k: v for k, v in deg_genes.items() if (k.startswith(donor) and k.endswith(f"_{cytokine}"))}
    adata_pred = adata_pred_all[adata_pred_all.obs["condition"]==condition]
    adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
    cond_orig = condition
    #adata_pred.write_h5ad(os.path.join(config_dict["training"]["out_dir"], f"{wandb.run.name}_{condition}_preds.h5ad"))
    out, distr_dict, gex_dict = compute_metrics(adata_ref=adata_ref, adata_pred_all_samples=adata_pred, donor_deg_dict=donor_deg_dict, adata_ood_true=adata_ood_true_cond, adata_ctrl=adata_ctrl)
    distr_dicts[condition] = distr_dict
    out_dicts[condition] = out
    gex_dicts[condition] = gex_dict
    #pd.DataFrame.from_dict(out, columns=[condition], orient="index").to_csv(os.path.join(config_dict["training"]["out_dir"], f"{wandb.run.name}_{condition}.csv"))
    #wandb.log({condition: out})

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
28 5360
1
28 5360
2
28 5360
3
28 5360
4
28 5360

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
18 5750
1
18 5750
2
18 5750
3
18 5750
4
18 5750

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
17 10237
1
17 10237
2
17 10237
3
17 10237
4
17 10237

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
26 9582
1
26 9582
2
26 9582
3
26 9582
4
26 9582

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
31 6851
1
31 6851
2
31 6851
3
31 6851
4
31 6851

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
33 8026
1
33 8026
2
33 8026
3
33 8026
4
33 8026

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
19 7011
1
19 7011
2
19 7011
3
19 7011
4
19 7011

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
29 7295
1
29 7295
2
29 7295
3
29 7295
4
29 7295

/tmp/ipykernel_4032555/3245858440.py:12: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata_pred.uns["donors_in_train"] = list(adata_to_append.obs["donor"].unique())
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

0
28 4816
1
28 4816
2
28 4816
3
28 4816
4
28 4816

In [56]:
out_dicts

{'Donor10_TWEAK': {'ood_e_distance': 35.5447244488651,
  'decoded_ood_r_squared': 0.919957531366401,
  'mean_decoded_r_sq_per_cell_type': 0.4521643511349637,
  'mean_e_distance_per_cell_type': 195.72721980231208,
  'mean_deg_r_sq_per_cell_type': -0.04257476681577403,
  'frechet_variance': 0.001247302391758072,
  'var_mean_gex': 1.5596884899287575e-05,
  'frechet_variance_CD4 Naive': 0.02306848429979835,
  'frechet_variance_CD56-dim NK': 0.050769653365612,
  'frechet_variance_CD14 Mono': 6.467025118162444,
  'frechet_variance_CD16 Mono': 18.259132944722147,
  'frechet_variance_CD4 Memory': 2245.8839704904494,
  'frechet_variance_B Intermediate/Memory': 0.07746515787512089,
  'frechet_variance_CD8 Naive': 7432.297164195087,
  'frechet_variance_NKT': 0.09304517368101095,
  'frechet_variance_CD56-bright NK': 0.08539655023361499,
  'frechet_variance_B Naive': 0.031565270771673454,
  'frechet_variance_CD8 Memory': 0.01565083063008546,
  'mean_frechet_variance_per_cell_type': 882.1167503517528,
  'var_mean_gex_CD4 Naive': 6.263300630744706e-05,
  'var_mean_deg_gex_CD4 Naive': 0.0005881629221445993,
  'var_mean_gex_CD56-dim NK': 8.603424923116083e-05,
  'var_mean_deg_gex_CD56-dim NK': 0.0006424730982620548,
  'var_mean_gex_CD14 Mono': 0.00037851279085428154,
  'var_mean_deg_gex_CD14 Mono': 0.0015600849787409138,
  'var_mean_gex_CD16 Mono': 0.0009503721272853836,
  'var_mean_deg_gex_CD16 Mono': 0.005050928577047206,
  'var_mean_gex_CD4 Memory': 0.009045151807536842,
  'var_mean_deg_gex_CD4 Memory': 0.08748832495451989,
  'var_mean_gex_B Intermediate/Memory': 0.00011419207892565851,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0007730854833482689,
  'var_mean_gex_CD8 Naive': 0.023185970255206363,
  'var_mean_deg_gex_CD8 Naive': 0.25330368343106924,
  'var_mean_gex_NKT': 0.00012123045519521853,
  'var_mean_deg_gex_NKT': 0.0009424784682699329,
  'var_mean_gex_CD56-bright NK': 9.60864447363661e-05,
  'var_mean_deg_gex_CD56-bright NK': 0.000593028364025772,
  'var_mean_gex_B Naive': 8.021707038547487e-05,
  'var_mean_deg_gex_B Naive': 0.0005680481305146625,
  'var_mean_gex_CD8 Memory': 7.008837943972578e-05,
  'var_mean_deg_gex_CD8 Memory': 0.0005603928127894081,
  'mean_var_mean_gex_per_cell_type': 0.003108226242282175,
  'mean_var_mean_deg_gex_per_cell_type': 0.03200642647461199},
 'Donor11_TWEAK': {'ood_e_distance': 46.854765764819966,
  'decoded_ood_r_squared': 0.8613339502560942,
  'mean_decoded_r_sq_per_cell_type': 0.2144957170029575,
  'mean_e_distance_per_cell_type': 275.1099824325537,
  'mean_deg_r_sq_per_cell_type': -0.5657326855563959,
  'frechet_variance': 0.0022831666061994284,
  'var_mean_gex': 2.1879582961444686e-05,
  'frechet_variance_CD56-dim NK': 0.4254760854478812,
  'frechet_variance_NKT': 0.08024631136211477,
  'frechet_variance_MAIT': 0.07284896512546674,
  'frechet_variance_CD4 Naive': 0.014370071020268634,
  'frechet_variance_B Naive': 0.037231409072425475,
  'frechet_variance_CD8 Naive': 0.03212097169201217,
  'frechet_variance_pDC': 0.09626584495401147,
  'frechet_variance_CD14 Mono': 0.022838012843473154,
  'frechet_variance_CD8 Memory': 31507.33152186258,
  'frechet_variance_B Intermediate/Memory': 0.0884408812136443,
  'frechet_variance_CD4 Memory': 0.1137772255411424,
  'frechet_variance_cDC': 0.07542122717717349,
  'mean_frechet_variance_per_cell_type': 2625.699213239003,
  'var_mean_gex_CD56-dim NK': 0.0001497959017363281,
  'var_mean_deg_gex_CD56-dim NK': 0.0012397809726128405,
  'var_mean_gex_NKT': 7.391142583777627e-05,
  'var_mean_deg_gex_NKT': 0.0007072907067867721,
  'var_mean_gex_MAIT': 0.0001114538278280624,
  'var_mean_deg_gex_MAIT': 0.0006775206081204633,
  'var_mean_gex_CD4 Naive': 6.325582939211043e-05,
  'var_mean_deg_gex_CD4 Naive': 0.0003358295972565608,
  'var_mean_gex_B Naive': 8.504755214990035e-05,
  'var_mean_deg_gex_B Naive': 0.0005317488527788679,
  'var_mean_gex_CD8 Naive': 8.975930211931018e-05,
  'var_mean_deg_gex_CD8 Naive': 0.0004923720158409044,
  'var_mean_gex_pDC': 0.00012860036581183675,
  'var_mean_deg_gex_pDC': 0.0006420739402643386,
  'var_mean_gex_CD14 Mono': 5.518555246157781e-05,
  'var_mean_deg_gex_CD14 Mono': 0.0003271343573119269,
  'var_mean_gex_CD8 Memory': 0.03228309235454138,
  'var_mean_deg_gex_CD8 Memory': 0.3836449227646014,
  'var_mean_gex_B Intermediate/Memory': 0.00011583199386590067,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0006951043473266512,
  'var_mean_gex_CD4 Memory': 0.00013448330944282428,
  'var_mean_deg_gex_CD4 Memory': 0.0008256064203779383,
  'var_mean_gex_cDC': 0.00011151581203527997,
  'var_mean_deg_gex_cDC': 0.0008073504507627026,
  'mean_var_mean_gex_per_cell_type': 0.0027834944356018576,
  'mean_var_mean_deg_gex_per_cell_type': 0.032577227919503446},
 'Donor12_TWEAK': {'ood_e_distance': 22.260514368778786,
  'decoded_ood_r_squared': 0.8366161820925762,
  'mean_decoded_r_sq_per_cell_type': 0.38034125961731535,
  'mean_e_distance_per_cell_type': 284.6316523122322,
  'mean_deg_r_sq_per_cell_type': -0.010025527648031139,
  'frechet_variance': 0.0037695075692190994,
  'var_mean_gex': 2.976706981537107e-05,
  'frechet_variance_CD4 Naive': 0.011822694327099615,
  'frechet_variance_CD16 Mono': 0.04340207343531536,
  'frechet_variance_CD8 Naive': 0.020685430383130834,
  'frechet_variance_Plasmablast': 9962.846321105264,
  'frechet_variance_Treg': 0.013148371013568085,
  'frechet_variance_CD4 Memory': 409.7880816692284,
  'frechet_variance_CD8 Memory': 0.10548869716280525,
  'frechet_variance_CD14 Mono': 0.0419258661921025,
  'frechet_variance_B Intermediate/Memory': 0.15075366576601978,
  'frechet_variance_MAIT': 0.0,
  'mean_frechet_variance_per_cell_type': 1037.3021629572772,
  'var_mean_gex_CD4 Naive': 5.2608337558261726e-05,
  'var_mean_deg_gex_CD4 Naive': 0.00028860969803976835,
  'var_mean_gex_CD16 Mono': 7.735920477523886e-05,
  'var_mean_deg_gex_CD16 Mono': 0.0003445769481207079,
  'var_mean_gex_CD8 Naive': 7.385916095360594e-05,
  'var_mean_deg_gex_CD8 Naive': 0.0004075475403016489,
  'var_mean_gex_Plasmablast': 0.02132066350010645,
  'var_mean_deg_gex_Plasmablast': 0.0836731584222343,
  'var_mean_gex_Treg': 6.6297808673877e-05,
  'var_mean_deg_gex_Treg': 0.0003542791271706245,
  'var_mean_gex_CD4 Memory': 0.005493152602477844,
  'var_mean_deg_gex_CD4 Memory': 0.01724566281628483,
  'var_mean_gex_CD8 Memory': 0.00010900492962392415,
  'var_mean_deg_gex_CD8 Memory': 0.00043117331039529717,
  'var_mean_gex_CD14 Mono': 7.837747348115726e-05,
  'var_mean_deg_gex_CD14 Mono': 0.00042410833659032644,
  'var_mean_gex_B Intermediate/Memory': 0.00011088867501052374,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0004569348968528746,
  'var_mean_gex_MAIT': 0.0,
  'var_mean_deg_gex_MAIT': 0.0,
  'mean_var_mean_gex_per_cell_type': 0.002738221169266088,
  'mean_var_mean_deg_gex_per_cell_type': 0.010362605109599039},
 'Donor3_TWEAK': {'ood_e_distance': 26.909145706587672,
  'decoded_ood_r_squared': 0.9365833628020942,
  'mean_decoded_r_sq_per_cell_type': 0.6832811192446008,
  'mean_e_distance_per_cell_type': 168.02402126941882,
  'mean_deg_r_sq_per_cell_type': 0.3355335384767727,
  'frechet_variance': 0.0027858545249096083,
  'var_mean_gex': 2.498520171406592e-05,
  'frechet_variance_CD4 Naive': 0.016139949158177864,
  'frechet_variance_CD4 Memory': 0.017011253658833176,
  'frechet_variance_CD14 Mono': 0.04238026023482993,
  'frechet_variance_CD8 Memory': 0.1504977311936127,
  'frechet_variance_CD8 Naive': 0.01538964359512716,
  'frechet_variance_NKT': 0.03958940187626309,
  'frechet_variance_CD56-dim NK': 0.08095359389430196,
  'frechet_variance_CD16 Mono': 0.028975305106594247,
  'frechet_variance_cDC': 0.13126506401422783,
  'frechet_variance_B Naive': 0.09267746759708462,
  'mean_frechet_variance_per_cell_type': 0.06148796703290525,
  'var_mean_gex_CD4 Naive': 5.911023470643019e-05,
  'var_mean_deg_gex_CD4 Naive': 0.00025302614280841115,
  'var_mean_gex_CD4 Memory': 6.200313648097962e-05,
  'var_mean_deg_gex_CD4 Memory': 0.0003054069151258368,
  'var_mean_gex_CD14 Mono': 6.52906537402209e-05,
  'var_mean_deg_gex_CD14 Mono': 0.00030069596856014297,
  'var_mean_gex_CD8 Memory': 0.0001367003630448249,
  'var_mean_deg_gex_CD8 Memory': 0.0006780409450749488,
  'var_mean_gex_CD8 Naive': 6.463737058431307e-05,
  'var_mean_deg_gex_CD8 Naive': 0.00027618026477451807,
  'var_mean_gex_NKT': 9.791138333859988e-05,
  'var_mean_deg_gex_NKT': 0.0005965047750848129,
  'var_mean_gex_CD56-dim NK': 0.0001150022797298253,
  'var_mean_deg_gex_CD56-dim NK': 0.0005794323324205691,
  'var_mean_gex_CD16 Mono': 7.178149855589805e-05,
  'var_mean_deg_gex_CD16 Mono': 0.0002950289931083789,
  'var_mean_gex_cDC': 0.00013121839820501072,
  'var_mean_deg_gex_cDC': 0.0006824885813564045,
  'var_mean_gex_B Naive': 0.00011700992033093527,
  'var_mean_deg_gex_B Naive': 0.0008750668057459218,
  'mean_var_mean_gex_per_cell_type': 9.206652387170378e-05,
  'mean_var_mean_deg_gex_per_cell_type': 0.0004841871724059945},
 'Donor5_TWEAK': {'ood_e_distance': 12.281724951760385,
  'decoded_ood_r_squared': 0.9356722316623289,
  'mean_decoded_r_sq_per_cell_type': 0.6019920154695617,
  'mean_e_distance_per_cell_type': 194.23337058444244,
  'mean_deg_r_sq_per_cell_type': 0.21434558599711692,
  'frechet_variance': 0.0021649064800276663,
  'var_mean_gex': 2.769449340348297e-05,
  'frechet_variance_CD4 Naive': 13.628546172520078,
  'frechet_variance_CD8 Naive': 9.952795507355285,
  'frechet_variance_B Intermediate/Memory': 0.0966580149719881,
  'frechet_variance_NKT': 0.009370671513576054,
  'frechet_variance_CD8 Memory': 0.5633032179886761,
  'frechet_variance_CD4 Memory': 13.893113572609257,
  'frechet_variance_CD14 Mono': 0.03030647185981647,
  'frechet_variance_CD56-dim NK': 0.14750441785472904,
  'mean_frechet_variance_per_cell_type': 4.790199755834176,
  'var_mean_gex_CD4 Naive': 0.0011129843759152156,
  'var_mean_deg_gex_CD4 Naive': 0.0036738947873519116,
  'var_mean_gex_CD8 Naive': 0.0011390947830245651,
  'var_mean_deg_gex_CD8 Naive': 0.004825435313751794,
  'var_mean_gex_B Intermediate/Memory': 0.00011021678386965827,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0006039638016090628,
  'var_mean_gex_NKT': 4.455209270696388e-05,
  'var_mean_deg_gex_NKT': 0.000171706917550879,
  'var_mean_gex_CD8 Memory': 0.00014478920112182908,
  'var_mean_deg_gex_CD8 Memory': 0.0003848197454253839,
  'var_mean_gex_CD4 Memory': 0.0007943259683523644,
  'var_mean_deg_gex_CD4 Memory': 0.00422469297145121,
  'var_mean_gex_CD14 Mono': 6.424027437488157e-05,
  'var_mean_deg_gex_CD14 Mono': 0.00024297107670718002,
  'var_mean_gex_CD56-dim NK': 0.00011327405594892079,
  'var_mean_deg_gex_CD56-dim NK': 0.00044992189778718204,
  'mean_var_mean_gex_per_cell_type': 0.0004404346919142998,
  'mean_var_mean_deg_gex_per_cell_type': 0.0018221758139543253},
 'Donor6_TWEAK': {'ood_e_distance': 55.04562406049463,
  'decoded_ood_r_squared': 0.8535453183069175,
  'mean_decoded_r_sq_per_cell_type': 0.6075196575637837,
  'mean_e_distance_per_cell_type': 186.47451308205433,
  'mean_deg_r_sq_per_cell_type': 0.22703570269974116,
  'frechet_variance': 0.0011112239351929937,
  'var_mean_gex': 1.791565741350852e-05,
  'frechet_variance_CD4 Naive': 4.266331485097371,
  'frechet_variance_CD14 Mono': 0.024434048067116857,
  'frechet_variance_CD4 Memory': 0.022824054826458627,
  'frechet_variance_MAIT': 0.018486240914693558,
  'frechet_variance_NKT': 0.03370349930886575,
  'frechet_variance_CD8 Naive': 7329.362216658879,
  'frechet_variance_CD56-dim NK': 0.04247496415662267,
  'frechet_variance_CD16 Mono': 0.02760563716419253,
  'frechet_variance_CD8 Memory': 0.034970654381566275,
  'frechet_variance_B Intermediate/Memory': 0.09091162917078931,
  'frechet_variance_B Naive': 0.04963693009494942,
  'mean_frechet_variance_per_cell_type': 666.724872345642,
  'var_mean_gex_CD4 Naive': 0.0004734761487939547,
  'var_mean_deg_gex_CD4 Naive': 0.004533531281118845,
  'var_mean_gex_CD14 Mono': 6.077367433240898e-05,
  'var_mean_deg_gex_CD14 Mono': 0.0004882830952179584,
  'var_mean_gex_CD4 Memory': 8.892041829368292e-05,
  'var_mean_deg_gex_CD4 Memory': 0.0008744053950576401,
  'var_mean_gex_MAIT': 6.384419700295817e-05,
  'var_mean_deg_gex_MAIT': 0.0005341027696005205,
  'var_mean_gex_NKT': 7.25844100051289e-05,
  'var_mean_deg_gex_NKT': 0.0006950191668019155,
  'var_mean_gex_CD8 Naive': 0.021004633242462514,
  'var_mean_deg_gex_CD8 Naive': 0.21546114105671907,
  'var_mean_gex_CD56-dim NK': 8.080616584805875e-05,
  'var_mean_deg_gex_CD56-dim NK': 0.000607543517176479,
  'var_mean_gex_CD16 Mono': 6.59642496787781e-05,
  'var_mean_deg_gex_CD16 Mono': 0.0005931358841806272,
  'var_mean_gex_CD8 Memory': 6.702704369189652e-05,
  'var_mean_deg_gex_CD8 Memory': 0.0005301114121950698,
  'var_mean_gex_B Intermediate/Memory': 0.00011922775912750928,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0011705945600231336,
  'var_mean_gex_B Naive': 0.0001017450980714718,
  'var_mean_deg_gex_B Naive': 0.0010403259334759685,
  'mean_var_mean_gex_per_cell_type': 0.002018091127937124,
  'mean_var_mean_deg_gex_per_cell_type': 0.020593472188324295},
 'Donor7_TWEAK': {'ood_e_distance': 47.18849006334449,
  'decoded_ood_r_squared': 0.8489630757820823,
  'mean_decoded_r_sq_per_cell_type': 0.25662624375219795,
  'mean_e_distance_per_cell_type': 264.52221056987366,
  'mean_deg_r_sq_per_cell_type': -0.17121701954163027,
  'frechet_variance': 0.0031668257164093622,
  'var_mean_gex': 2.999277572557417e-05,
  'frechet_variance_MAIT': 0.019099845880026892,
  'frechet_variance_CD8 Naive': 42.12072945437351,
  'frechet_variance_CD4 Naive': 0.0043437094469959935,
  'frechet_variance_Treg': 0.017434643019611732,
  'frechet_variance_B Naive': 0.03872515407882329,
  'frechet_variance_CD4 Memory': 15063.994387150504,
  'frechet_variance_CD8 Memory': 0.022014090312551426,
  'frechet_variance_B Intermediate/Memory': 0.0418733596223314,
  'mean_frechet_variance_per_cell_type': 1888.2823259259048,
  'var_mean_gex_MAIT': 7.926101555227278e-05,
  'var_mean_deg_gex_MAIT': 0.0005180813684463966,
  'var_mean_gex_CD8 Naive': 0.0017478207856437742,
  'var_mean_deg_gex_CD8 Naive': 0.010728601726490556,
  'var_mean_gex_CD4 Naive': 4.2470755797846676e-05,
  'var_mean_deg_gex_CD4 Naive': 0.00020353792344809528,
  'var_mean_gex_Treg': 8.096015429375321e-05,
  'var_mean_deg_gex_Treg': 0.0005044788870576908,
  'var_mean_gex_B Naive': 8.656174412727769e-05,
  'var_mean_deg_gex_B Naive': 0.0006509257478973514,
  'var_mean_gex_CD4 Memory': 0.027897581985087065,
  'var_mean_deg_gex_CD4 Memory': 0.25315385022080655,
  'var_mean_gex_CD8 Memory': 7.744135419940908e-05,
  'var_mean_deg_gex_CD8 Memory': 0.00040602665172466407,
  'var_mean_gex_B Intermediate/Memory': 9.221485692052152e-05,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0006515369759111738,
  'mean_var_mean_gex_per_cell_type': 0.00376303908145274,
  'mean_var_mean_deg_gex_per_cell_type': 0.0333521299377228},
 'Donor8_TWEAK': {'ood_e_distance': 84.49618814890593,
  'decoded_ood_r_squared': 0.8019988218790723,
  'mean_decoded_r_sq_per_cell_type': 0.5518333583746026,
  'mean_e_distance_per_cell_type': 218.5365953997238,
  'mean_deg_r_sq_per_cell_type': 0.1694346427843805,
  'frechet_variance': 0.0011334158677381442,
  'var_mean_gex': 1.7763755236881493e-05,
  'frechet_variance_CD16 Mono': 0.04501074188781517,
  'frechet_variance_CD8 Memory': 0.008854574534629102,
  'frechet_variance_cDC': 0.10840999272054336,
  'frechet_variance_CD4 Memory': 0.0061621528486192345,
  'frechet_variance_CD8 Naive': 0.01970579051526347,
  'frechet_variance_CD4 Naive': 0.010312045422931203,
  'frechet_variance_CD14 Mono': 0.01954917003174184,
  'frechet_variance_B Intermediate/Memory': 0.10063766965327856,
  'frechet_variance_CD56-dim NK': 0.0353549975497667,
  'frechet_variance_Treg': 0.01734394112206467,
  'frechet_variance_other': 0.3952322205246962,
  'frechet_variance_MAIT': 0.12842358889889383,
  'mean_frechet_variance_per_cell_type': 0.07458307380918694,
  'var_mean_gex_CD16 Mono': 7.581153779331694e-05,
  'var_mean_deg_gex_CD16 Mono': 0.0003997790442602736,
  'var_mean_gex_CD8 Memory': 5.324732424376824e-05,
  'var_mean_deg_gex_CD8 Memory': 0.00028209396383438624,
  'var_mean_gex_cDC': 0.00012734452831536462,
  'var_mean_deg_gex_cDC': 0.0005979650116337488,
  'var_mean_gex_CD4 Memory': 4.5500770882929114e-05,
  'var_mean_deg_gex_CD4 Memory': 0.00023430150654696273,
  'var_mean_gex_CD8 Naive': 6.271549796953289e-05,
  'var_mean_deg_gex_CD8 Naive': 0.0003090512420060091,
  'var_mean_gex_CD4 Naive': 5.704660126259805e-05,
  'var_mean_deg_gex_CD4 Naive': 0.00022618557533702843,
  'var_mean_gex_CD14 Mono': 5.281242966298757e-05,
  'var_mean_deg_gex_CD14 Mono': 0.00023988362501397052,
  'var_mean_gex_B Intermediate/Memory': 0.00012275846809955233,
  'var_mean_deg_gex_B Intermediate/Memory': 0.0007212687830247759,
  'var_mean_gex_CD56-dim NK': 8.40971689238269e-05,
  'var_mean_deg_gex_CD56-dim NK': 0.00046335157349422436,
  'var_mean_gex_Treg': 7.382706276679064e-05,
  'var_mean_deg_gex_Treg': 0.00044243054018433835,
  'var_mean_gex_other': 0.0001589963217764776,
  'var_mean_deg_gex_other': 0.0006257790457270254,
  'var_mean_gex_MAIT': 0.0001356186651613363,
  'var_mean_deg_gex_MAIT': 0.0007323621273909923,
  'mean_var_mean_gex_per_cell_type': 8.748136473820676e-05,
  'mean_var_mean_deg_gex_per_cell_type': 0.00043953766987114455},
 'Donor9_TWEAK': {'ood_e_distance': 56.7191152922009,
  'decoded_ood_r_squared': 0.8316898343428824,
  'mean_decoded_r_sq_per_cell_type': 0.5527814640330092,
  'mean_e_distance_per_cell_type': 220.0490604381961,
  'mean_deg_r_sq_per_cell_type': 0.34734824515458307,
  'frechet_variance': 0.002674371518605721,
  'var_mean_gex': 2.54765428023456e-05,
  'frechet_variance_CD8 Memory': 133.95022557550394,
  'frechet_variance_CD8 Naive': 0.011099052001097036,
  'frechet_variance_CD4 Memory': 0.0078157422555463,
  'frechet_variance_MAIT': 0.0826239535938376,
  'frechet_variance_ILC': 0.0418803494133812,
  'frechet_variance_Treg': 0.06765993488454963,
  'frechet_variance_CD4 Naive': 0.028779042414874913,
  'frechet_variance_CD14 Mono': 0.048798491864219445,
  'frechet_variance_NKT': 367.75745840275965,
  'frechet_variance_CD16 Mono': 0.039718482044357205,
  'frechet_variance_B Naive': 0.058446344665151834,
  'frechet_variance_CD56-dim NK': 0.05739489879194748,
  'mean_frechet_variance_per_cell_type': 41.84599168918271,
  'var_mean_gex_CD8 Memory': 0.0029223758932462795,
  'var_mean_deg_gex_CD8 Memory': 0.018077403171249676,
  'var_mean_gex_CD8 Naive': 6.382731882388901e-05,
  'var_mean_deg_gex_CD8 Naive': 0.00047141207135510086,
  'var_mean_gex_CD4 Memory': 5.277211266382022e-05,
  'var_mean_deg_gex_CD4 Memory': 0.0004374065901998293,
  'var_mean_gex_MAIT': 0.00011250477238036425,
  'var_mean_deg_gex_MAIT': 0.0008827825112173613,
  'var_mean_gex_ILC': 9.463333011646185e-05,
  'var_mean_deg_gex_ILC': 0.0006891535307156329,
  'var_mean_gex_Treg': 0.00010037441406541006,
  'var_mean_deg_gex_Treg': 0.000653193284491277,
  'var_mean_gex_CD4 Naive': 7.628375257424195e-05,
  'var_mean_deg_gex_CD4 Naive': 0.00045809965752805783,
  'var_mean_gex_CD14 Mono': 8.232051810911373e-05,
  'var_mean_deg_gex_CD14 Mono': 0.0005182598065531912,
  'var_mean_gex_NKT': 0.008110487202727947,
  'var_mean_deg_gex_NKT': 0.0608611763777274,
  'var_mean_gex_CD16 Mono': 7.641127639586926e-05,
  'var_mean_deg_gex_CD16 Mono': 0.0004685185137757637,
  'var_mean_gex_B Naive': 0.00010778318194432517,
  'var_mean_deg_gex_B Naive': 0.0007171358364687409,
  'var_mean_gex_CD56-dim NK': 0.00010393676654944339,
  'var_mean_deg_gex_CD56-dim NK': 0.0006840709523800617,
  'mean_var_mean_gex_per_cell_type': 0.0009919758782997638,
  'mean_var_mean_deg_gex_per_cell_type': 0.007076551025305172}}

In [58]:
df = pd.DataFrame(columns=["e_distance", "e_distance_var", "r_sq_per_cell_type", "r_sq_per_cell_type_var", "deg_r_sq", "deg_r_sq_var"])

In [61]:
for i, (k, v) in enumerate(out_dicts.items()):
    df.loc[i, :] = {
        "e_distance": v["ood_e_distance"],
        "e_distance_var": v["frechet_variance"],
        "r_sq_per_cell_type": v["mean_decoded_r_sq_per_cell_type"],
        "r_sq_per_cell_type_var": v["mean_var_mean_gex_per_cell_type"],
        "deg_r_sq": v["mean_deg_r_sq_per_cell_type"],
        "deg_r_sq_var": v["mean_var_mean_deg_gex_per_cell_type"],
    }

In [68]:
df

,e_distance,e_distance_var,r_sq_per_cell_type,r_sq_per_cell_type_var,deg_r_sq,deg_r_sq_var,neg_deg_r_sq,neg_r_sq_per_cell_type
0,35.544724,0.001247,0.452164,0.003108,-0.042575,0.032006,1.042575,0.996892
1,46.854766,0.002283,0.214496,0.002783,-0.565733,0.032577,1.565733,0.997217
2,22.260514,0.00377,0.380341,0.002738,-0.010026,0.010363,1.010026,0.997262
3,26.909146,0.002786,0.683281,0.000092,0.335534,0.000484,0.664466,0.999908
4,12.281725,0.002165,0.601992,0.00044,0.214346,0.001822,0.785654,0.99956
5,55.045624,0.001111,0.60752,0.002018,0.227036,0.020593,0.772964,0.997982
6,47.18849,0.003167,0.256626,0.003763,-0.171217,0.033352,1.171217,0.996237
7,84.496188,0.001133,0.551833,0.000087,0.169435,0.00044,0.830565,0.999913
8,56.719115,0.002674,0.552781,0.000992,0.347348,0.007077,0.652652,0.999008

In [63]:
df["neg_deg_r_sq"] = 1-df["deg_r_sq"]
df["neg_r_sq_per_cell_type"] = 1-df["r_sq_per_cell_type_var"]

In [72]:
cal_log_dict = {}
cal_log_dict["e_dist_calibration"] = df[["e_distance", "e_distance_var"]].corr(method="spearman").iloc[0,1]
cal_log_dict["gex_calibration"] = df[["r_sq_per_cell_type", "r_sq_per_cell_type_var"]].corr(method="spearman").iloc[0,1]
cal_log_dict["deg_calibration"] = df[["neg_deg_r_sq", "deg_r_sq_var"]].corr(method="spearman").iloc[0,1]

In [73]:
cal_log_dict

{'e_dist_calibration': -0.4,
 'gex_calibration': -0.7,
 'deg_calibration': 0.6833333333333333}

In [50]:
df_tmp = pd.DataFrame.from_dict(out, columns=[condition], orient="index")
df_tmp["Donor"]

                                     Donor9_TWEAK
ood_e_distance                          56.719115
decoded_ood_r_squared                    0.831690
mean_decoded_r_sq_per_cell_type          0.552781
mean_e_distance_per_cell_type          220.049060
mean_deg_r_sq_per_cell_type              0.347348
frechet_variance                              NaN
var_mean_gex                                  NaN
frechet_variance_CD8 Memory            133.950226
frechet_variance_CD8 Naive               0.011099
frechet_variance_CD4 Memory              0.007816
frechet_variance_MAIT                    0.082624
frechet_variance_ILC                     0.041880
frechet_variance_Treg                    0.067660
frechet_variance_CD4 Naive               0.028779
frechet_variance_CD14 Mono               0.048798
frechet_variance_NKT                   367.757458
frechet_variance_CD16 Mono               0.039718
frechet_variance_B Naive                 0.058446
frechet_variance_CD56-dim NK             0.057395
mean_frechet_variance_per_cell_type     41.845992
var_mean_gex_CD8 Memory                  0.002922
var_mean_deg_gex_CD8 Memory              0.018077
var_mean_gex_CD8 Naive                   0.000064
var_mean_deg_gex_CD8 Naive               0.000471
var_mean_gex_CD4 Memory                  0.000053
var_mean_deg_gex_CD4 Memory              0.000437
var_mean_gex_MAIT                        0.000113
var_mean_deg_gex_MAIT                    0.000883
var_mean_gex_ILC                         0.000095
var_mean_deg_gex_ILC                     0.000689
var_mean_gex_Treg                        0.000100
var_mean_deg_gex_Treg                    0.000653
var_mean_gex_CD4 Naive                   0.000076
var_mean_deg_gex_CD4 Naive               0.000458
var_mean_gex_CD14 Mono                   0.000082
var_mean_deg_gex_CD14 Mono               0.000518
var_mean_gex_NKT                         0.008110
var_mean_deg_gex_NKT                     0.060861
var_mean_gex_CD16 Mono                   0.000076
var_mean_deg_gex_CD16 Mono               0.000469
var_mean_gex_B Naive                     0.000108
var_mean_deg_gex_B Naive                 0.000717
var_mean_gex_CD56-dim NK                 0.000104
var_mean_deg_gex_CD56-dim NK             0.000684
mean_var_mean_gex_per_cell_type          0.000992
mean_var_mean_deg_gex_per_cell_type      0.007077

In [45]:
adata_ood_true_cond.X = adata_ood_true_cond.X.toarray()

/home/icb/dominik.klein/mambaforge/envs/cellflow/lib/python3.12/site-packages/anndata/_core/anndata.py:617: FutureWarning: You are attempting to set `X` to a matrix on a view which has non-unique indices. The resulting `adata.X` will likely not equal the value to which you set it. To avoid this potential issue, please make a copy of the data first. In the future, this operation will throw an error.
  warnings.warn(msg, FutureWarning, stacklevel=1)

In [23]:
adata_pred.obs["condition"].value_counts()

condition
Donor10_TWEAK    140
Name: count, dtype: int64

In [24]:
adata_pred.obs["sample"].value_counts()

sample
0    28
1    28
2    28
3    28
4    28
Name: count, dtype: int64

In [27]:
adata_ood_true.obs["condition"].value_counts()

condition
Donor9_TWEAK    4816
Name: count, dtype: int64

In [56]:
np.isnan(adata_ood_true.X.toarray()).sum()

0

In [44]:
adata_ood_true

View of AnnData object with n_obs × n_vars = 0 × 2000
    obs: 'sample', 'species', 'gene_count', 'tscp_count', 'mread_count', 'bc1_wind', 'bc2_wind', 'bc3_wind', 'bc1_well', 'bc2_well', 'bc3_well', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'total_counts_MT', 'pct_counts_MT', 'log1p_total_counts_MT', 'donor', 'cytokine', 'treatment', 'cell_type', 'condition', 'is_control', 'cell_type_new', 'donor_cell_type'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'donor_one_hot', 'esm2_embeddings', 'hvg', 'log1p', 'pca'
    obsm: 'X_pca'
    varm: 'PCs', 'X_mean'
    layers: 'counts'

In [42]:
adata_pred.obs["sample"].value_counts()

sample
0    10000
1    10000
2    10000
3    10000
4    10000
Name: count, dtype: int64

In [21]:
adata_pred_all.obs["sample"].value_counts()

sample
0    90000
1    90000
2    90000
3    90000
4    90000
Name: count, dtype: int64

In [153]:
adata_base.uns

{'donor_one_hot': {'Donor1': array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'Donor10': array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'Donor11': array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'Donor12': array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  'Donor2': array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  'Donor3': array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
  'Donor4': array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
  'Donor5': array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
  'Donor6': array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
  'Donor7': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]),
  'Donor8': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
  'Donor9': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])},
 'esm2_embeddings': {'4-1BBL': array([ 0.06635367, -0.08944552,  0.0325702 , ...,  0.00990983,
         -0.0871339 ,  0.01538398]),
  'ADSF': array([ 0.01920176, -0.05948664, -0.00102595, ...,  0.02550411,
         -0.09670118,  0.00064903]),
  'APRIL': array([-0.00519803, -0.10985713,  0.01845249, ...,  0.03945353,
         -0.16356128, -0.05738389]),
  'BAFF': array([ 0.03038253, -0.09596335, -0.04508404, ...,  0.06645241,
         -0.07733674, -0.09367309]),
  'C3a': array([ 0.09511378, -0.04532898,  0.07307669, ..., -0.00484946,
         -0.04920399,  0.05552371]),
  'C5a': array([ 0.06620854, -0.04665874,  0.05456881, ...,  0.00733562,
         -0.10505915,  0.07733899]),
  'CD27L': array([ 0.07348149, -0.09206714,  0.05452932, ...,  0.02864902,
         -0.1146683 , -0.0207436 ]),
  'CD30L': array([-0.01256566, -0.06422756,  0.08285663, ...,  0.03195513,
         -0.13527282,  0.0281936 ]),
  'CD40L': array([ 0.03177214, -0.06253324,  0.0326427 , ...,  0.08658189,
         -0.08414166, -0.10830674]),
  'CT-1': array([ 0.05736688, -0.03024629, -0.05416125, ...,  0.07470252,
         -0.05787468, -0.12179071]),
  'Decorin': array([-0.05458623, -0.0196926 ,  0.06930956, ..., -0.02005091,
         -0.08747175, -0.00930543]),
  'EBI3': array([ 0.0233736 ,  0.08817893, -0.02361775, ...,  0.03543465,
         -0.13076216, -0.01851152]),
  'EGF': array([ 0.0360274 ,  0.0168316 ,  0.08625314, ...,  0.01816369,
         -0.17829333,  0.02462191]),
  'EPO': array([ 0.03111472, -0.07692412, -0.01744605, ...,  0.04612758,
         -0.08220736, -0.09539114]),
  'FGF-beta': array([-0.01636455, -0.0973009 , -0.02211582, ..., -0.0779302 ,
         -0.26007241,  0.08122525]),
  'FLT3L': array([-0.00510596, -0.10069638, -0.08524719, ...,  0.02830173,
         -0.12541783, -0.28836372]),
  'FasL': array([-0.01296736, -0.03121445,  0.04507203, ...,  0.06993005,
         -0.13028069,  0.02982992]),
  'G-CSF': array([ 0.04653721, -0.0394686 ,  0.00485675, ...,  0.02842662,
         -0.13506612, -0.11846881]),
  'GDNF': array([-0.07226645, -0.1062794 ,  0.0422984 , ...,  0.0847197 ,
         -0.1423129 , -0.1149727 ]),
  'GITRL': array([ 0.04445656, -0.02454672,  0.05151693, ...,  0.04478568,
         -0.16527905,  0.04583899]),
  'GM-CSF': array([ 0.02124861, -0.05843202, -0.01579322, ...,  0.00656341,
         -0.08296123, -0.06190897]),
  'HGF': array([ 0.00386856, -0.05113854, -0.03338093, ...,  0.05368049,
         -0.10922303, -0.03054053]),
  'IFN-alpha1': array([ 0.05245034, -0.06895248, -0.0452822 , ...,  0.00725202,
         -0.16386116, -0.23743783]),
  'IFN-beta': array([ 0.06942932, -0.00096388, -0.03953616, ...,  0.02572711,
         -0.14011295, -0.06274437]),
  'IFN-epsilon': array([ 0.09039252,  0.00244514, -0.01588265, ...,  0.01665524,
         -0.17386171, -0.10135497]),
  'IFN-gamma': array([ 0.0032107 ,  0.11701933,  0.02903703, ...,  0.03524049,
         -0.1301834 , -0.01807887]),
  'IFN-lambda1': array([ 0.0112186 , -0.08147442,  0.02849656, ...,  0.00892402,
         -0.0819397 , -0.0275989 ]),
  'IFN-lambda2': array([ 0.05341343, -0.10085719, -0.02271684, ...,  0.05877211,
         -0.12938264, -0.12614135]),
  'IFN-lambda3': array([ 0.05305598, -0.10546111, -0.05415016, ...,  0.07060257,
         -0.1225957 , -0.14678743]),
  'IFN-omega': array([ 0.1130704 , -0.05280471, -0.02133964, ...,  0.0233727 ,
         -0.18634562, -0.17058487]),
  'IGF-1': array([-0.09399705, -0.05496966,  0.03293975, ...,  0.03976451,
         -0.1471366 , -0.19757205]),
  'IL-1-alpha': array([-0.04313148,  0.03435136,  0.03138655, ..., -0.02086148,
         -0.15035546,  0.03556716]),
  'IL-1-beta': array([-0.04828889, -0.02873874,  0.0512272 , ..., -0.01657895,
         -0.16671738,  0.04112332]),
  'IL-10': array([ 0.00189338, -0.05195639, -0.00400383, ...,  0.0155625 ,
         -0.06861629, -0.12565234]),
  'IL-11': array([-0.03595658, -0.11129679, -0.07167356, ...,  0.08521359,
         -0.08361325, -0.18388553]),
  'IL-12': array([ 0.00532083, -0.05190123,  0.00658711, ...,  0.0880788 ,
         -0.06323847, -0.09488155]),
  'IL-13': array([ 0.05424365, -0.07386643,  0.01174124, ..., -0.00015797,
         -0.11944705, -0.08662404]),
  'IL-15': array([ 0.0557865 , -0.03930802,  0.03905998, ..., -0.05277991,
         -0.17781194,  0.00527069]),
  'IL-16': array([-0.00500105, -0.03186487,  0.02060602, ...,  0.00185243,
         -0.13897713,  0.07727315]),
  'IL-17A': array([-0.02192325, -0.03946196, -0.00808891, ...,  0.08954411,
         -0.25128868, -0.05016682]),
  'IL-17B': array([-0.01158643, -0.10620809,  0.02109993, ...,  0.04127064,
         -0.15920492, -0.06744748]),
  'IL-17C': array([ 0.00566159, -0.09441171,  0.02199811, ...,  0.02403447,
         -0.15707564, -0.05727362]),
  'IL-17D': array([-0.04338126, -0.17705765, -0.07196359, ...,  0.13736233,
         -0.13503571, -0.17870946]),
  'IL-17E': array([-0.0193723 , -0.08297183,  0.02615288, ...,  0.05061546,
         -0.22077946, -0.0594049 ]),
  'IL-17F': array([ 0.02574611, -0.04143754,  0.03449884, ...,  0.06224002,
         -0.2425808 , -0.05794894]),
  'IL-18': array([ 0.02020182,  0.02460739, -0.03985202, ...,  0.046055  ,
         -0.06673454, -0.05168073]),
  'IL-19': array([ 0.04033951, -0.05420472,  0.02813643, ...,  0.03072011,
         -0.12702839, -0.13169214]),
  'IL-1Ra': array([ 0.06136138,  0.00977729,  0.00328003, ...,  0.04668418,
         -0.18409665,  0.00066644]),
  'IL-2': array([ 0.08390682, -0.01322199, -0.00946199, ..., -0.02242345,
         -0.08114517, -0.01690393]),
  'IL-20': array([ 0.03450391, -0.04672588,  0.02848604, ...,  0.04964635,
         -0.10577101, -0.13359798]),
  'IL-21': array([ 0.03988849, -0.02222174,  0.00305494, ..., -0.01210255,
         -0.12055534, -0.01676388]),
  'IL-22': array([ 0.02244904, -0.00562771,  0.00499478, ...,  0.0331705 ,
         -0.13303271, -0.08644256]),
  'IL-23': array([ 0.05085238, -0.00928573,  0.03619492, ..., -0.0397699 ,
         -0.1600872 , -0.06789009]),
  'IL-24': array([ 0.05475257, -0.01831551,  0.07237785, ...,  0.01157808,
         -0.15193482, -0.07304808]),
  'IL-26': array([ 0.04373083, -0.01205167,  0.04238459, ..., -0.00912836,
         -0.12732223, -0.02182663]),
  'IL-27': array([ 0.01378666, -0.07649391, -0.03726536, ...,  0.05622633,
         -0.15533292, -0.1360015 ]),
  'IL-3': array([ 0.07048132, -0.04762851, -0.00489678, ..., -0.01046375,
         -0.12400322, -0.00334259]),
  'IL-31': array([-0.00820073,  0.12869538,  0.02485639, ...,  0.04700598,
         -0.24805602, -0.02751684]),
  'IL-32-beta': array([ 0.06659442, -0.102067  ,  0.0536163 , ...,  0.0221924 ,
         -0.16429015, -0.07409074]),
  'IL-33': array([ 0.01366029,  0.05295523,  0.07470889, ..., -0.03674088,
         -0.24888103,  0.03972109]),
  'IL-34': array([ 0.04898405, -0.0773766 , -0.00149652, ...,  0.06593686,
         -0.16348632, -0.09536261]),
  'IL-35': array([ 0.00557061, -0.04730326,  0.00079894, ...,  0.06798936,
         -0.04869774, -0.10196228]),
  'IL-36-alpha': array([ 0.08272478,  0.0494761 , -0.01411646, ...,  0.07635123,
         -0.09857236, -0.00150135]),
  'IL-36Ra': array([ 0.07412606,  0.04047345, -0.02552891, ...,  0.09409653,
         -0.13041675, -0.09834392]),
  'IL-4': array([ 0.0568883 , -0.06120029, -0.00658906, ...,  0.01167335,
         -0.07728172, -0.05029091]),
  'IL-5': array([ 0.03488432, -0.07194874,  0.00690801, ...,  0.00761871,
         -0.09227213, -0.04060582]),
  'IL-6': array([ 0.0622874 , -0.00491217, -0.00899084, ...,  0.03263969,
         -0.10387964, -0.05525691]),
  'IL-7': array([ 0.07009537, -0.0593134 ,  0.00042692, ...,  0.01808297,
         -0.13318744, -0.01897864]),
  'IL-8': array([-0.01429685, -0.04390007, -0.02277639, ..., -0.02185971,
         -0.1844424 , -0.11528353]),
  'IL-9': array([ 0.04053672, -0.01048372,  0.03490425, ...,  0.016843  ,
         -0.25159574, -0.03161394]),
  'LIF': array([ 0.0440927 , -0.04673396, -0.02121317, ...,  0.04628748,
         -0.10726684, -0.10942213]),
  'LIGHT': array([-0.06718283,  0.00253733,  0.05712503, ...,  0.08142015,
         -0.19390494, -0.18341047]),
  'LT-alpha': array([ 0.07446954, -0.07054647,  0.00799104, ...,  0.02241498,
         -0.13174936,  0.00097131]),
  'LT-alpha1-beta2': array([ 0.0578304 , -0.07835037,  0.01898382, ...,  0.00858678,
         -0.12269858,  0.03425966]),
  'LT-alpha2-beta1': array([-0.0589228 ,  0.04641173, -0.10645812, ..., -0.0728801 ,
         -0.07242696, -0.19570825]),
  'LT-beta': array([-0.02528222, -0.15922715,  0.0105503 , ...,  0.03210836,
         -0.04969179, -0.10514463]),
  'Leptin': array([ 0.07349487, -0.02209873,  0.00473814, ..., -0.00772461,
         -0.1332161 , -0.0644915 ]),
  'M-CSF': array([-0.01566501, -0.07478194, -0.07033414, ...,  0.07146814,
         -0.08890589, -0.23659454]),
  'Noggin': array([-0.05556903, -0.07153214,  0.06150003, ..., -0.0108887 ,
         -0.05796646, -0.01600976]),
  'OSM': array([ 0.06937265, -0.04092275, -0.00289203, ...,  0.07850537,
         -0.14222418, -0.11003674]),
  'OX40L': array([-0.01687433, -0.07756998,  0.00810468, ...,  0.07408338,
         -0.15866245, -0.12708092]),
  'PRL': array([ 0.05545178, -0.02315999, -0.00517783, ...,  0.01554512,
         -0.12445698, -0.06198731]),
  'PSPN': array([ 0.03167473, -0.08472662, -0.0438098 , ...,  0.06961963,
         -0.21737334, -0.11570549]),
  'RANKL': array([ 0.01384657, -0.01979259,  0.05556908, ...,  0.01787621,
         -0.05903014,  0.00241554]),
  'SCF': array([ 0.10423854, -0.02282211, -0.01803694, ...,  0.04466762,
         -0.09656697, -0.10986615]),
  'TGF-beta1': array([-0.01401122,  0.00131909,  0.03541976, ..., -0.0257134 ,
         -0.10505526, -0.01292962]),
  'TL1A': array([ 0.04976304, -0.07102517,  0.07301555, ..., -0.03803796,
         -0.14937341,  0.02691477]),
  'TNF-alpha': array([-0.01388079,  0.07168908,  0.1651388 , ..., -0.00748942,
         -0.0839035 , -0.00974038]),
  'TPO': array([ 0.00525983, -0.07215632,  0.09330501, ...,  0.02647239,
         -0.09429618, -0.00747985]),
  'TRAIL': array([ 0.00898676, -0.06978927,  0.05800851, ...,  0.03336399,
         -0.09029657, -0.02620572]),
  'TSLP': array([ 0.05735582, -0.02291679,  0.00410948, ..., -0.0380422 ,
         -0.09028511,  0.00484859]),
  'TWEAK': array([ 0.04800208, -0.08821861, -0.05445807, ...,  0.08559639,
         -0.03497461, -0.12155386]),
  'VEGF': array([ 0.01854835, -0.08227297,  0.02200293, ..., -0.01805243,
         -0.17225415,  0.02845273])},
 'hvg': {'flavor': 'seurat'},
 'log1p': {},
 'pca': {'params': {'zero_center': False,
   'use_highly_variable': True,
   'mask_var': 'highly_variable',
   'layer': 'X_centered'},
  'variance': array([188.46165  ,  61.880466 ,  55.52986  ,  24.209473 ,  17.21894  ,
          14.293869 ,  12.566167 ,  10.36484  ,   9.41224  ,   8.552972 ,
           7.770436 ,   7.6227574,   6.768126 ,   6.359528 ,   6.08717  ,
           5.5270824,   5.3069572,   4.968565 ,   4.909887 ,   4.692266 ,
           4.55069  ,   4.4476876,   4.4085293,   4.3043337,   4.123515 ,
           4.0616727,   4.0369554,   3.9774685,   3.8968654,   3.85726  ,
           3.8065097,   3.744381 ,   3.6852736,   3.6639645,   3.6119182,
           3.5600379,   3.5421832,   3.4903972,   3.4352481,   3.4396875,
           3.3328867,   3.3134167,   3.2655406,   3.251066 ,   3.2050698,
           3.1634486,   3.1019645,   3.053481 ,   2.995158 ,   3.0112307,
           3.014455 ,   2.980239 ,   2.9290621,   2.894796 ,   2.8932502,
           2.8550339,   2.8283174,   2.8165784,   2.787437 ,   2.7401495,
           2.735106 ,   2.7098188,   2.7043638,   2.6974466,   2.6709743,
           2.6726713,   2.6154568,   2.5985062,   2.590215 ,   2.5464203,
           2.5570276,   2.5122998,   2.4980042,   2.4870548,   2.46959  ,
           2.464459 ,   2.445244 ,   2.4302893,   2.406399 ,   2.4010775,
           2.364799 ,   2.3620234,   2.3440335,   2.3259237,   2.3396385,
           2.3066924,   2.2950435,   2.299506 ,   2.2878416,   2.2573142,
           2.2582788,   2.257003 ,   2.243843 ,   2.189334 ,   2.199168 ,
           2.2199783,   2.1870682,   2.1769414,   2.16735  ,   2.1647573],
        dtype=float32),
  'variance_ratio': array([0.13396958, 0.04398825, 0.03947387, 0.01720951, 0.01224023,
         0.01016092, 0.00893277, 0.00736793, 0.00669077, 0.00607995,
         0.00552368, 0.0054187 , 0.00481118, 0.00452072, 0.00432712,
         0.00392897, 0.0037725 , 0.00353195, 0.00349023, 0.00333554,
         0.0032349 , 0.00316168, 0.00313384, 0.00305977, 0.00293124,
         0.00288727, 0.0028697 , 0.00282742, 0.00277012, 0.00274197,
         0.00270589, 0.00266173, 0.00261971, 0.00260456, 0.00256756,
         0.00253068, 0.00251799, 0.00248118, 0.00244198, 0.00244513,
         0.00236921, 0.00235537, 0.00232134, 0.00231105, 0.00227835,
         0.00224876, 0.00220506, 0.00217059, 0.00212913, 0.00214056,
         0.00214285, 0.00211853, 0.00208215, 0.00205779, 0.00205669,
         0.00202953, 0.00201053, 0.00200219, 0.00198147, 0.00194786,
         0.00194427, 0.0019263 , 0.00192242, 0.0019175 , 0.00189868,
         0.00189989, 0.00185922, 0.00184717, 0.00184128, 0.00181014,
         0.00181768, 0.00178589, 0.00177573, 0.00176794, 0.00175553,
         0.00175188, 0.00173822, 0.00172759, 0.00171061, 0.00170683,
         0.00168104, 0.00167906, 0.00166628, 0.0016534 , 0.00166315,
         0.00163973, 0.00163145, 0.00163462, 0.00162633, 0.00160463,
         0.00160532, 0.00160441, 0.00159505, 0.00155631, 0.0015633 ,
         0.00157809, 0.0015547 , 0.0015475 , 0.00154068, 0.00153884],
        dtype=float32)}}

In [154]:
adata_rest.uns["split_info"].keys() #[idx_given_cytokine]["donors_to_impute"]

dict_keys(['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '4', '40', '41', '42', '5', '6', '7', '8', '9'])

In [155]:
adata_rest.uns["split_info"]["0"]

{'donors_to_impute': array(['Donor6', 'Donor9', 'Donor8', 'Donor11', 'Donor10', 'Donor5',
        'Donor7', 'Donor1', 'Donor3', 'Donor2', 'Donor4', 'Donor12'],
       dtype=object),
 'donors_to_train_data': array([], dtype=float64)}

In [161]:
for k in adata_rest.uns["split_info"].keys():
    print(set(adata_rest.uns["split_info"][k]["donors_to_train_data"]) == set(adata_rest2.uns["split_info"][k]["donors_to_train_data"]))

True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
False
True
True
True
True
True
True
True
True
True
False
True
True
True
False
False
False
False
False

In [165]:
k="4"
print(set(adata_rest.uns["split_info"][k]["donors_to_train_data"]))
print(set(adata_rest2.uns["split_info"][k]["donors_to_train_data"]))

{'Donor9', 'Donor10'}
{'Donor7', 'Donor4'}

In [157]:
for k,v in adata_rest.uns["split_info"].items():
    print(len(v["donors_to_train_data"]), len(v["donors_to_impute"]))
#adata_rest.uns["split_info"]["1"]

0 12
1 11
4 8
4 8
4 8
5 7
5 7
5 7
6 6
6 6
6 6
7 5
1 11
7 5
7 5
8 4
8 4
8 4
9 3
9 3
9 3
10 2
10 2
1 11
10 2
11 1
11 1
11 1
11 1
11 1
11 1
11 1
11 1
11 1
2 10
11 1
11 1
11 1
2 10
2 10
3 9
3 9
3 9

In [158]:
cytokine_held_out2 = "VEGF"
idx_given_cytokine = "7"
control_key = "is_control"

adata_rest2 = sc.read_h5ad(f"/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/new_cytokine/adata_rest_{cytokine_held_out2}.h5ad")

In [168]:
for cyto in ['IFN-beta','IFN-epsilon','C5a', '4-1BBL','ADSF','APRIL','BAFF', 'Noggin','OSM','OX40L', 'IL-13','IL-15']:
    adata_rest = sc.read_h5ad(f"/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/new_cytokine/adata_rest_{cyto}.h5ad")
    for k,v in adata_rest.uns["split_info"].items():
        if len(v["donors_to_impute"]) in [11, 12]:
            print(cyto, k)

IFN-beta 0
IFN-beta 1
IFN-beta 2
IFN-beta 3
IFN-epsilon 0
IFN-epsilon 1
IFN-epsilon 2
IFN-epsilon 3
C5a 0
C5a 1
C5a 2
C5a 3
4-1BBL 0
4-1BBL 1
4-1BBL 2
4-1BBL 3
ADSF 0
ADSF 1
ADSF 2
ADSF 3
APRIL 0
APRIL 1
APRIL 2
APRIL 3
BAFF 0
BAFF 1
BAFF 2
BAFF 3
Noggin 0
Noggin 1
Noggin 2
Noggin 3
OSM 0
OSM 1
OSM 2
OSM 3
OX40L 0
OX40L 1
OX40L 2
OX40L 3
IL-13 0
IL-13 1
IL-13 2
IL-13 3
IL-15 0
IL-15 1
IL-15 2
IL-15 3

In [166]:
for k,v in adata_rest2.uns["split_info"].items():
    print(k, len(v["donors_to_impute"]))

0 12
1 11
10 8
11 8
12 8
13 7
14 7
15 7
16 6
17 6
18 6
19 5
2 11
20 5
21 5
22 4
23 4
24 4
25 3
26 3
27 3
28 2
29 2
3 11
30 2
31 1
32 1
33 1
34 1
35 1
36 1
37 1
38 1
39 1
4 10
40 1
41 1
42 1
5 10
6 10
7 9
8 9
9 9

In [167]:
for k,v in adata_rest.uns["split_info"].items():
    print(k, len(v["donors_to_impute"]))

0 12
1 11
10 8
11 8
12 8
13 7
14 7
15 7
16 6
17 6
18 6
19 5
2 11
20 5
21 5
22 4
23 4
24 4
25 3
26 3
27 3
28 2
29 2
3 11
30 2
31 1
32 1
33 1
34 1
35 1
36 1
37 1
38 1
39 1
4 10
40 1
41 1
42 1
5 10
6 10
7 9
8 9
9 9